import json
from sqlalchemy.orm import Session
from app.models import CoordinationModel


COORDINATION_MODELS = [
    {
        "name": "Accountable Care Organization",
        "abbreviation": "ACO",
        "category": "managed_care",
        "description": "Provider-led organization that accepts accountability for the cost and quality of care for a defined population. Ties financial incentives to quality metrics and total cost of care.",
        "target_population": ["Medicare beneficiaries", "Medicaid enrollees", "Dual eligibles", "Commercially insured"],
        "domains_covered": ["health", "behavioral_health"],
        "authority_type": "federal_waiver",
        "funding_sources": ["Medicare shared savings", "Medicaid managed care capitation", "Commercial payer contracts"],
        "typical_budget_range": {"min": 5000000, "max": 500000000, "unit": "annual"},
        "staffing_model": {
            "care_coordinators": "1:200 patients",
            "primary_care": "1:1500 panel",
            "behavioral_health": "1:500 patients",
            "data_analysts": "2-5 per ACO",
            "admin": "5-15% of staff"
        },
        "governance_structure": "Board with provider majority, quality committee, finance committee, patient advisory council",
        "key_features": ["Shared savings/risk", "Quality benchmarks", "Care coordination", "Data analytics", "Population health management"],
        "limitations": ["Health-focused only", "Complex financial models", "Requires scale", "Provider consolidation risk", "Slow to address social determinants"],
        "evidence_rating": "strong",
        "example_sites": ["Pioneer ACOs (Medicare)", "MSSP Track 1+", "Blue Cross Blue Shield Alternative Quality Contracts"],
        "regulatory_requirements": ["CMS certification", "Quality reporting", "Financial solvency", "Anti-kickback safe harbors"],
        "timeline_to_launch": "12-18 months",
        "political_feasibility": "high",
    },
    {
        "name": "Health Home",
        "abbreviation": "HH",
        "category": "community_based",
        "description": "State Medicaid option under ACA Section 2703 providing comprehensive care coordination for people with chronic conditions. Builds on primary care medical home model with enhanced coordination across medical, behavioral, and social services.",
        "target_population": ["People with 2+ chronic conditions", "People with 1 serious mental illness", "People with 1 chronic condition at risk for another"],
        "domains_covered": ["health", "behavioral_health", "housing", "income"],
        "authority_type": "state_plan",
        "funding_sources": ["Medicaid enhanced match (90% for first 8 quarters)", "State Medicaid funds", "Supplemental grants"],
        "typical_budget_range": {"min": 1000000, "max": 50000000, "unit": "annual"},
        "staffing_model": {
            "care_managers": "1:50 patients",
            "health_home_director": "1 per site",
            "community_health_workers": "1:75 patients",
            "nurses": "1:100 patients",
            "peer_specialists": "1:100 patients"
        },
        "governance_structure": "Lead health home entity (FQHC, hospital, or community MH center) with network of downstream providers",
        "key_features": ["Comprehensive care management", "Care coordination", "Health promotion", "Transitional care", "Individual/family support", "Referral to community/social services"],
        "limitations": ["Medicaid-only population", "Enhanced match time-limited", "Requires state plan amendment", "Staffing challenges in rural areas"],
        "evidence_rating": "moderate",
        "example_sites": ["New York Health Home program", "Missouri Primary Care Health Home", "Rhode Island Health Home"],
        "regulatory_requirements": ["State Plan Amendment", "CMS approval", "Chronic condition eligibility criteria", "Quality reporting"],
        "timeline_to_launch": "9-15 months",
        "political_feasibility": "high",
    },
    {
        "name": "Program of All-Inclusive Care for the Elderly",
        "abbreviation": "PACE",
        "category": "specialized",
        "description": "Capitated managed care model providing comprehensive medical and social services to frail elderly individuals who would otherwise require nursing home care. Features adult day centers as hub for service delivery.",
        "target_population": ["Adults 55+", "Nursing home eligible", "Able to live safely in community with PACE support"],
        "domains_covered": ["health", "behavioral_health", "housing", "income", "social_support"],
        "authority_type": "federal_waiver",
        "funding_sources": ["Medicare capitation", "Medicaid capitation", "Private pay"],
        "typical_budget_range": {"min": 3000000, "max": 80000000, "unit": "annual"},
        "staffing_model": {
            "interdisciplinary_team": "1 team per 120 participants",
            "physicians": "1:120 participants",
            "nurses": "1:40 participants",
            "social_workers": "1:60 participants",
            "therapists": "1:60 participants",
            "aides": "1:20 participants",
            "drivers": "1:30 participants"
        },
        "governance_structure": "PACE organization with board, medical director, IDT leadership, participant advisory council",
        "key_features": ["Full-risk capitation", "Interdisciplinary teams", "Adult day center hub", "Home care", "All medical/social services included", "No out-of-pocket costs"],
        "limitations": ["Age 55+ only", "Requires day center infrastructure", "Capital intensive startup", "Geographic catchment limits", "Slow enrollment growth"],
        "evidence_rating": "strong",
        "example_sites": ["On Lok (San Francisco)", "LIFE Philadelphia", "InnovAge (Colorado)"],
        "regulatory_requirements": ["CMS PACE agreement", "State Medicaid agreement", "Three-way agreement", "Quality measures", "Financial solvency"],
        "timeline_to_launch": "18-36 months",
        "political_feasibility": "moderate",
    },
    {
        "name": "Wraparound / High-Fidelity Wraparound",
        "abbreviation": "WRAP",
        "category": "community_based",
        "description": "Intensive, individualized care planning and management process for children and youth with complex behavioral health and social needs. Emphasizes natural supports and family voice.",
        "target_population": ["Children with SED", "Youth with complex multi-system involvement", "Families with multiple service needs"],
        "domains_covered": ["health", "behavioral_health", "education", "child_welfare", "justice"],
        "authority_type": "local_agreement",
        "funding_sources": ["Medicaid 1915(c) waiver", "SAMHSA grants", "State children's mental health", "Child welfare IV-E", "Education IDEA funds"],
        "typical_budget_range": {"min": 500000, "max": 20000000, "unit": "annual"},
        "staffing_model": {
            "wraparound_facilitators": "1:8-10 families",
            "family_partners": "1:15 families",
            "youth_partners": "1:15 youth",
            "supervisors": "1:6-8 facilitators",
            "care_coordinators": "1:12 families"
        },
        "governance_structure": "Community collaborative with cross-system governance body, family/youth representation required",
        "key_features": ["Family-driven", "Youth-guided", "Strengths-based", "Natural supports", "Culturally competent", "Team-based planning", "Community-based services"],
        "limitations": ["Youth/family focus only", "Fidelity difficult to maintain", "Workforce training intensive", "Funding braiding complex"],
        "evidence_rating": "strong",
        "example_sites": ["Milwaukee Wraparound", "New Jersey CSOC", "Maryland Care Management Entity"],
        "regulatory_requirements": ["Varies by funding stream", "Fidelity standards (Wraparound Fidelity Index)", "Cross-system MOUs"],
        "timeline_to_launch": "6-12 months",
        "political_feasibility": "high",
    },
    {
        "name": "Coordinated Community Response",
        "abbreviation": "CCR",
        "category": "community_based",
        "description": "Multi-agency coordinated approach to complex social problems (originally domestic violence, now expanded). Aligns protocols, data sharing, and responses across systems without creating a new entity.",
        "target_population": ["Domestic violence survivors", "People experiencing homelessness", "Re-entry populations", "Opioid use disorder"],
        "domains_covered": ["justice", "housing", "health", "income", "child_welfare"],
        "authority_type": "local_agreement",
        "funding_sources": ["Federal grants (OVW, HUD CoC)", "State funding", "Local government", "Foundation grants"],
        "typical_budget_range": {"min": 200000, "max": 5000000, "unit": "annual"},
        "staffing_model": {
            "coordinator": "1-2 per CCR",
            "data_analyst": "0.5-1 per CCR",
            "agency_liaisons": "1 per participating agency",
            "training_specialist": "0.5-1 per CCR"
        },
        "governance_structure": "Steering committee with agency heads, working groups by topic, community advisory board",
        "key_features": ["Protocol alignment", "Shared accountability", "Cross-training", "Data sharing agreements", "Community-driven", "Low infrastructure cost"],
        "limitations": ["Voluntary participation", "No fiscal authority", "Depends on agency champions", "Turnover vulnerability", "Limited enforcement"],
        "evidence_rating": "moderate",
        "example_sites": ["Duluth Model (DV)", "HUD Continuum of Care", "Drug courts"],
        "regulatory_requirements": ["Inter-agency MOUs", "Data sharing agreements", "Confidentiality protocols"],
        "timeline_to_launch": "3-6 months",
        "political_feasibility": "high",
    },
    {
        "name": "Managed Care Organization",
        "abbreviation": "MCO",
        "category": "managed_care",
        "description": "Insurance-based model where a managed care entity receives capitated payments to provide or arrange for a defined set of services. Manages financial risk and coordinates care through provider networks.",
        "target_population": ["Medicaid enrollees", "CHIP beneficiaries", "Dual eligibles", "Commercial populations"],
        "domains_covered": ["health", "behavioral_health"],
        "authority_type": "state_plan",
        "funding_sources": ["Medicaid capitation", "Premium revenue", "Reinsurance"],
        "typical_budget_range": {"min": 50000000, "max": 5000000000, "unit": "annual"},
        "staffing_model": {
            "medical_director": "1 per MCO",
            "care_managers": "1:300 members",
            "utilization_review": "1:2000 members",
            "network_management": "3-10 per MCO",
            "quality": "3-5 per MCO"
        },
        "governance_structure": "Corporate board, medical advisory committee, member advisory council, state oversight",
        "key_features": ["Capitated risk", "Provider networks", "Utilization management", "Quality incentives", "Care management programs"],
        "limitations": ["Profit motive tensions", "Administrative complexity", "Prior authorization burden", "Network adequacy issues", "Limited social determinant focus"],
        "evidence_rating": "strong",
        "example_sites": ["Centene", "Molina Healthcare", "AmeriHealth Caritas"],
        "regulatory_requirements": ["State contract", "CMS managed care rule (42 CFR 438)", "NCQA/URAC accreditation", "MLR requirements"],
        "timeline_to_launch": "18-24 months",
        "political_feasibility": "moderate",
    },
    {
        "name": "Community Health Worker Hub",
        "abbreviation": "CHW",
        "category": "community_based",
        "description": "Community-anchored model using trained community health workers as the primary point of contact for people navigating multiple systems. Bridges clinical, social, and governmental services through trusted community members.",
        "target_population": ["Underserved communities", "Immigrant/refugee populations", "People with complex social needs", "Uninsured/underinsured"],
        "domains_covered": ["health", "housing", "income", "education", "immigration"],
        "authority_type": "local_agreement",
        "funding_sources": ["Medicaid CHW reimbursement", "Community benefit", "Grants", "Health system investment", "Payer partnerships"],
        "typical_budget_range": {"min": 300000, "max": 8000000, "unit": "annual"},
        "staffing_model": {
            "community_health_workers": "1:50-100 clients",
            "supervisors": "1:6-8 CHWs",
            "navigator_specialists": "1:150 clients",
            "program_director": "1 per hub"
        },
        "governance_structure": "Community-based organization with advisory board including community members, health systems, and payers",
        "key_features": ["Culturally matched", "Trust-based relationships", "System navigation", "Social determinant screening", "Advocacy", "Low cost"],
        "limitations": ["Low reimbursement", "Limited clinical authority", "Turnover", "Scope limitations", "Sustainability challenges"],
        "evidence_rating": "moderate",
        "example_sites": ["Penn Center for CHW", "MassHealth CHW program", "Oregon Traditional Health Workers"],
        "regulatory_requirements": ["State CHW certification (varies)", "Medicaid billing codes", "Supervision requirements"],
        "timeline_to_launch": "3-6 months",
        "political_feasibility": "high",
    },
    {
        "name": "Social Impact Bond / Pay for Success",
        "abbreviation": "SIB",
        "category": "hybrid",
        "description": "Outcomes-based financing model where private investors fund social interventions upfront, and government pays investors back (with returns) only if pre-defined outcomes are achieved. Shifts financial risk from government to investors.",
        "target_population": ["Chronically homeless", "Re-entry populations", "At-risk youth", "Pre-K children"],
        "domains_covered": ["housing", "justice", "education", "child_welfare"],
        "authority_type": "contractual",
        "funding_sources": ["Private investor capital", "Government outcome payments", "Philanthropic support (subordinate)"],
        "typical_budget_range": {"min": 2000000, "max": 50000000, "unit": "project_total"},
        "staffing_model": {
            "project_manager": "1 per SIB",
            "evaluator": "Independent third party",
            "intermediary": "1 organization",
            "service_providers": "Varies by intervention",
            "fiscal_agent": "1 per SIB"
        },
        "governance_structure": "Intermediary (project manager) between investors, government, evaluator, and service providers",
        "key_features": ["Outcomes-based payment", "Private capital", "Rigorous evaluation", "Innovation incentive", "Government risk reduction"],
        "limitations": ["High transaction costs", "Complex contracting", "Cherry-picking risk", "Limited scale", "Long timeline to results"],
        "evidence_rating": "emerging",
        "example_sites": ["Rikers Island (NYC)", "Utah Pre-K", "South Carolina Nurse-Family Partnership"],
        "regulatory_requirements": ["Government authorizing legislation", "Outcome metrics agreement", "Independent evaluation protocol"],
        "timeline_to_launch": "12-24 months",
        "political_feasibility": "moderate",
    },
    {
        "name": "Integrated Care for Dual Eligibles",
        "abbreviation": "DSNP+",
        "category": "managed_care",
        "description": "Specialized managed care approach for people eligible for both Medicare and Medicaid. Integrates physical health, behavioral health, and long-term services through a single plan with aligned incentives.",
        "target_population": ["Dual eligible individuals (Medicare + Medicaid)", "People with disabilities", "Frail elderly"],
        "domains_covered": ["health", "behavioral_health", "housing", "income"],
        "authority_type": "federal_waiver",
        "funding_sources": ["Medicare capitation", "Medicaid capitation", "Integrated rate setting"],
        "typical_budget_range": {"min": 20000000, "max": 2000000000, "unit": "annual"},
        "staffing_model": {
            "care_coordinators": "1:75 members",
            "LTSS_coordinators": "1:50 members",
            "behavioral_health": "1:200 members",
            "pharmacists": "1:1000 members",
            "social_workers": "1:150 members"
        },
        "governance_structure": "Health plan with joint Medicare-Medicaid oversight, member advisory, ombudsman program",
        "key_features": ["Single point of contact", "Aligned incentives", "LTSS integration", "Behavioral health carve-in", "Social determinant screening"],
        "limitations": ["Complex regulatory environment", "Two-payer coordination", "Enrollment complexity", "Data system integration"],
        "evidence_rating": "moderate",
        "example_sites": ["FIDE SNP plans", "Massachusetts One Care", "California Cal MediConnect"],
        "regulatory_requirements": ["CMS DSNP contract", "State Medicaid contract", "Medicare Part D", "NCQA SNP standards"],
        "timeline_to_launch": "18-24 months",
        "political_feasibility": "moderate",
    },
    {
        "name": "Cross-System Data Integration Hub",
        "abbreviation": "CDIH",
        "category": "hybrid",
        "description": "Technology-centered coordination model that creates a shared data infrastructure across human service systems. Enables real-time identification of multi-system users, coordinated case management, and population-level analytics.",
        "target_population": ["Multi-system involved individuals", "Frequent utilizers", "People in crisis", "System-wide population"],
        "domains_covered": ["health", "justice", "housing", "income", "education", "child_welfare"],
        "authority_type": "local_agreement",
        "funding_sources": ["Government IT budgets", "Federal grants (ONC, HHS)", "Health system investment", "Payer data-sharing agreements"],
        "typical_budget_range": {"min": 1000000, "max": 30000000, "unit": "annual"},
        "staffing_model": {
            "chief_data_officer": "1 per hub",
            "data_engineers": "3-8 per hub",
            "data_governance": "1-2 per hub",
            "privacy_officer": "1 per hub",
            "system_navigators": "1:100 clients",
            "analytics": "2-5 per hub"
        },
        "governance_structure": "Multi-agency data governance board, privacy committee, technical steering committee, community oversight",
        "key_features": ["Real-time data matching", "Cross-system alerts", "Coordinated case plans", "Population analytics", "Privacy framework", "Predictive risk stratification"],
        "limitations": ["Privacy/consent barriers", "Technical complexity", "Agency resistance", "Sustainability funding", "Governance politics"],
        "evidence_rating": "emerging",
        "example_sites": ["Allegheny County DHS Data Warehouse", "Camden Coalition", "Hennepin County HMIS+"],
        "regulatory_requirements": ["HIPAA/42 CFR Part 2 compliance", "Data sharing agreements per system", "IRB for research use", "State privacy laws"],
        "timeline_to_launch": "12-24 months",
        "political_feasibility": "low",
    },
]


def seed_all(db: Session) -> dict:
    counts = {}

    existing = db.query(CoordinationModel).count()
    if existing == 0:
        for m in COORDINATION_MODELS:
            model = CoordinationModel(
                name=m["name"],
                abbreviation=m["abbreviation"],
                category=m["category"],
                description=m["description"],
                target_population=json.dumps(m["target_population"]),
                domains_covered=json.dumps(m["domains_covered"]),
                authority_type=m["authority_type"],
                funding_sources=json.dumps(m["funding_sources"]),
                typical_budget_range=json.dumps(m["typical_budget_range"]),
                staffing_model=json.dumps(m["staffing_model"]),
                governance_structure=m["governance_structure"],
                key_features=json.dumps(m["key_features"]),
                limitations=json.dumps(m["limitations"]),
                evidence_rating=m["evidence_rating"],
                example_sites=json.dumps(m["example_sites"]),
                regulatory_requirements=json.dumps(m["regulatory_requirements"]),
                timeline_to_launch=m["timeline_to_launch"],
                political_feasibility=m["political_feasibility"],
            )
            db.add(model)
        db.commit()
        counts["coordination_models"] = len(COORDINATION_MODELS)
    else:
        counts["coordination_models"] = f"exists ({existing})"

    return counts
