"""
DOMES Innovation Laboratory — SQLAlchemy ORM models.

Four core tables:
  - Teammate   : the 12 innovation domain specialists
  - Innovation : breakthrough ideas generated by teammates
  - Collaboration : cross-domain joint efforts
  - LabSession : focused research sessions
"""

from datetime import datetime, timezone

from sqlalchemy import (
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import relationship

from database import Base


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class Teammate(Base):
    __tablename__ = "teammates"

    id = Column(Integer, primary_key=True, autoincrement=True)
    slug = Column(String(64), unique=True, nullable=False, index=True)
    name = Column(String(128), nullable=False)
    title = Column(String(256), nullable=False)
    domain = Column(String(128), nullable=False)
    description = Column(Text, nullable=False, default="")
    color = Column(String(7), nullable=False, default="#475569")
    icon_symbol = Column(String(8), nullable=False, default="*")
    status = Column(String(16), nullable=False, default="active")  # active | standby | generating
    created_at = Column(DateTime, nullable=False, default=_utcnow)

    innovations = relationship(
        "Innovation", back_populates="teammate", cascade="all, delete-orphan"
    )

    def to_dict(self, include_innovations: bool = False):
        d = {
            "id": self.id,
            "slug": self.slug,
            "name": self.name,
            "title": self.title,
            "domain": self.domain,
            "description": self.description,
            "color": self.color,
            "icon_symbol": self.icon_symbol,
            "status": self.status,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "innovation_count": len(self.innovations) if self.innovations else 0,
        }
        if include_innovations:
            d["innovations"] = [i.to_dict() for i in self.innovations]
        return d


class Innovation(Base):
    __tablename__ = "innovations"

    id = Column(Integer, primary_key=True, autoincrement=True)
    teammate_id = Column(Integer, ForeignKey("teammates.id"), nullable=False, index=True)
    title = Column(String(512), nullable=False)
    summary = Column(Text, nullable=False, default="")
    domain = Column(String(128), nullable=False, index=True)
    category = Column(String(128), nullable=False, default="general")
    impact_level = Column(Integer, nullable=False, default=3)       # 1-5
    feasibility = Column(Integer, nullable=False, default=3)        # 1-5
    novelty = Column(Integer, nullable=False, default=3)            # 1-5
    time_horizon = Column(String(16), nullable=False, default="medium")  # near | medium | far
    status = Column(String(16), nullable=False, default="draft")    # draft | review | approved | archived
    details = Column(Text, nullable=False, default="{}")            # JSON text
    tags = Column(Text, nullable=False, default="")                 # comma-separated
    created_at = Column(DateTime, nullable=False, default=_utcnow)
    updated_at = Column(DateTime, nullable=False, default=_utcnow, onupdate=_utcnow)

    teammate = relationship("Teammate", back_populates="innovations")

    def to_dict(self):
        import json

        try:
            details_parsed = json.loads(self.details) if self.details else {}
        except (json.JSONDecodeError, TypeError):
            details_parsed = {}

        return {
            "id": self.id,
            "teammate_id": self.teammate_id,
            "title": self.title,
            "summary": self.summary,
            "domain": self.domain,
            "category": self.category,
            "impact_level": self.impact_level,
            "feasibility": self.feasibility,
            "novelty": self.novelty,
            "time_horizon": self.time_horizon,
            "status": self.status,
            "details": details_parsed,
            "tags": [t.strip() for t in self.tags.split(",") if t.strip()] if self.tags else [],
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }


class Collaboration(Base):
    __tablename__ = "collaborations"

    id = Column(Integer, primary_key=True, autoincrement=True)
    title = Column(String(512), nullable=False)
    summary = Column(Text, nullable=False, default="")
    status = Column(String(16), nullable=False, default="proposed")  # proposed | active | completed
    teammate_ids = Column(Text, nullable=False, default="")          # comma-separated teammate IDs
    innovations = Column(Text, nullable=False, default="[]")         # JSON text — innovation IDs and contributions
    created_at = Column(DateTime, nullable=False, default=_utcnow)

    def to_dict(self):
        import json

        try:
            innovations_parsed = json.loads(self.innovations) if self.innovations else []
        except (json.JSONDecodeError, TypeError):
            innovations_parsed = []

        return {
            "id": self.id,
            "title": self.title,
            "summary": self.summary,
            "status": self.status,
            "teammate_ids": [int(x.strip()) for x in self.teammate_ids.split(",") if x.strip()] if self.teammate_ids else [],
            "innovations": innovations_parsed,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }


class LabSession(Base):
    __tablename__ = "lab_sessions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(256), nullable=False)
    focus_domain = Column(String(128), nullable=False, default="general")
    status = Column(String(16), nullable=False, default="planning")  # planning | active | review | complete
    participants = Column(Text, nullable=False, default="")          # comma-separated teammate slugs
    findings = Column(Text, nullable=False, default="{}")            # JSON text
    started_at = Column(DateTime, nullable=True)
    completed_at = Column(DateTime, nullable=True)

    def to_dict(self):
        import json

        try:
            findings_parsed = json.loads(self.findings) if self.findings else {}
        except (json.JSONDecodeError, TypeError):
            findings_parsed = {}

        return {
            "id": self.id,
            "name": self.name,
            "focus_domain": self.focus_domain,
            "status": self.status,
            "participants": [s.strip() for s in self.participants.split(",") if s.strip()] if self.participants else [],
            "findings": findings_parsed,
            "started_at": self.started_at.isoformat() if self.started_at else None,
            "completed_at": self.completed_at.isoformat() if self.completed_at else None,
        }
