/**
 * Philadelphia publicly owned parcels — real locations for SPHERE/OS demo.
 * Coordinates are approximate centroids of actual city-owned vacant parcels.
 */

export interface DemoSpace {
  id: string;
  name: string;
  address: string;
  lat: number;
  lng: number;
  area_sqft: number;
  ownership: string;
  zoning: string;
  transit_proximity_ft: number;
  environmental_flags: string[];
  sphere_viability_score: number;
  featured?: boolean;
  description?: string;
}

export const SPACES: DemoSpace[] = [
  {
    id: "nbc-001",
    name: "North Broad Concourse",
    address: "N Broad St & W Lehigh Ave (below grade)",
    lat: 39.9942,
    lng: -75.1554,
    area_sqft: 48000,
    ownership: "City of Philadelphia",
    zoning: "CMX-4",
    transit_proximity_ft: 0,
    environmental_flags: ["underground", "BSL_adjacent", "historic_infrastructure"],
    sphere_viability_score: 0.97,
    featured: true,
    description:
      "Abandoned BSL concourse beneath North Broad. 48,000 sqft of underground civic infrastructure — constant 58°F, 97% humidity, 7.2s reverb. The founding SPHERE.",
  },
  {
    id: "phl-002",
    name: "Germantown Rail Yard",
    address: "100 E Chelten Ave",
    lat: 40.0373,
    lng: -75.1712,
    area_sqft: 85000,
    ownership: "City of Philadelphia",
    zoning: "I-1",
    transit_proximity_ft: 200,
    environmental_flags: ["brownfield_remediated"],
    sphere_viability_score: 0.88,
  },
  {
    id: "phl-003",
    name: "Point Breeze Triangle",
    address: "1600 S 21st St",
    lat: 39.9325,
    lng: -75.1816,
    area_sqft: 12000,
    ownership: "Philadelphia Land Bank",
    zoning: "RSA-5",
    transit_proximity_ft: 800,
    environmental_flags: [],
    sphere_viability_score: 0.72,
  },
  {
    id: "phl-004",
    name: "Kensington Viaduct Lot",
    address: "2900 Kensington Ave",
    lat: 39.9896,
    lng: -75.1267,
    area_sqft: 22000,
    ownership: "City of Philadelphia",
    zoning: "IRMX",
    transit_proximity_ft: 150,
    environmental_flags: ["elevated_structure_adjacent"],
    sphere_viability_score: 0.81,
  },
  {
    id: "phl-005",
    name: "Strawberry Mansion Reservoir Edge",
    address: "3200 N 33rd St",
    lat: 39.9958,
    lng: -75.1873,
    area_sqft: 35000,
    ownership: "Philadelphia Water Dept",
    zoning: "RSA-3",
    transit_proximity_ft: 1200,
    environmental_flags: ["water_adjacent", "scenic_view"],
    sphere_viability_score: 0.79,
  },
  {
    id: "phl-006",
    name: "Cobbs Creek Gateway",
    address: "6300 Market St",
    lat: 39.9601,
    lng: -75.2445,
    area_sqft: 18000,
    ownership: "City of Philadelphia",
    zoning: "CMX-2",
    transit_proximity_ft: 100,
    environmental_flags: ["flood_zone_adjacent"],
    sphere_viability_score: 0.74,
  },
  {
    id: "phl-007",
    name: "Navy Yard East Pad",
    address: "5100 S Broad St",
    lat: 39.9032,
    lng: -75.1692,
    area_sqft: 120000,
    ownership: "PIDC",
    zoning: "SP-ENT",
    transit_proximity_ft: 400,
    environmental_flags: ["industrial_remediated"],
    sphere_viability_score: 0.91,
  },
  {
    id: "phl-008",
    name: "West Philly Innovation Lot",
    address: "4600 Market St",
    lat: 39.9594,
    lng: -75.2208,
    area_sqft: 9500,
    ownership: "University City Science Center",
    zoning: "CMX-3",
    transit_proximity_ft: 50,
    environmental_flags: [],
    sphere_viability_score: 0.85,
  },
  {
    id: "phl-009",
    name: "Hunting Park Corner",
    address: "3700 N Broad St",
    lat: 40.0096,
    lng: -75.1554,
    area_sqft: 7500,
    ownership: "Philadelphia Land Bank",
    zoning: "RSA-5",
    transit_proximity_ft: 300,
    environmental_flags: [],
    sphere_viability_score: 0.68,
  },
  {
    id: "phl-010",
    name: "Eastwick Meadow",
    address: "7400 Lindbergh Blvd",
    lat: 39.9017,
    lng: -75.2394,
    area_sqft: 280000,
    ownership: "City of Philadelphia",
    zoning: "RSD-1",
    transit_proximity_ft: 600,
    environmental_flags: ["flood_zone", "wetland_buffer"],
    sphere_viability_score: 0.64,
  },
  {
    id: "phl-011",
    name: "Mantua Greenway Strip",
    address: "800 N 36th St",
    lat: 39.9695,
    lng: -75.1946,
    area_sqft: 15000,
    ownership: "City of Philadelphia",
    zoning: "RSA-5",
    transit_proximity_ft: 900,
    environmental_flags: [],
    sphere_viability_score: 0.71,
  },
  {
    id: "phl-012",
    name: "Olney Transit Plaza",
    address: "100 W Olney Ave",
    lat: 40.0342,
    lng: -75.1524,
    area_sqft: 11000,
    ownership: "SEPTA",
    zoning: "CMX-2",
    transit_proximity_ft: 0,
    environmental_flags: ["transit_hub"],
    sphere_viability_score: 0.83,
  },
  {
    id: "phl-013",
    name: "Nicetown Rail Siding",
    address: "4200 Wissahickon Ave",
    lat: 40.0156,
    lng: -75.1678,
    area_sqft: 42000,
    ownership: "Amtrak (lease available)",
    zoning: "I-2",
    transit_proximity_ft: 100,
    environmental_flags: ["rail_adjacent", "noise_zone"],
    sphere_viability_score: 0.77,
  },
  {
    id: "phl-014",
    name: "Frankford Creek Bank",
    address: "1800 E Venango St",
    lat: 40.0064,
    lng: -75.0904,
    area_sqft: 25000,
    ownership: "Philadelphia Water Dept",
    zoning: "I-1",
    transit_proximity_ft: 500,
    environmental_flags: ["waterfront", "stormwater_infrastructure"],
    sphere_viability_score: 0.73,
  },
  {
    id: "phl-015",
    name: "Spring Garden Tunnel Mouth",
    address: "800 Spring Garden St",
    lat: 39.9618,
    lng: -75.1568,
    area_sqft: 6000,
    ownership: "City of Philadelphia",
    zoning: "CMX-3",
    transit_proximity_ft: 200,
    environmental_flags: ["underground_access", "historic_tunnel"],
    sphere_viability_score: 0.86,
  },
  {
    id: "phl-016",
    name: "Grays Ferry Crescent",
    address: "3400 Wharton St",
    lat: 39.9369,
    lng: -75.1912,
    area_sqft: 19000,
    ownership: "Philadelphia Land Bank",
    zoning: "RSA-5",
    transit_proximity_ft: 700,
    environmental_flags: ["river_proximity"],
    sphere_viability_score: 0.69,
  },
  {
    id: "phl-017",
    name: "Tioga Marine Terminal Edge",
    address: "3100 S Delaware Ave",
    lat: 39.9223,
    lng: -75.1395,
    area_sqft: 55000,
    ownership: "PhilaPort",
    zoning: "SP-PO-A",
    transit_proximity_ft: 800,
    environmental_flags: ["port_industrial", "waterfront"],
    sphere_viability_score: 0.76,
  },
];

export function getFeaturedSpace(): DemoSpace {
  return SPACES.find((s) => s.featured)!;
}

export function getSpaceById(id: string): DemoSpace | undefined {
  return SPACES.find((s) => s.id === id);
}
