/**
 * DomeExport.tsx
 *
 * Export functionality for the Dome visualization:
 * - "Export as Image" button: renders SVG to canvas, then to PNG download
 * - Adds title, date, and "Generated by DOMES" watermark
 * - "Copy Link" for shareable URL
 */

import { useCallback, useState } from 'react';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

interface DomeExportProps {
  /** Ref to the SVG element to capture */
  svgRef: React.RefObject<SVGSVGElement | null>;
  /** Profile name for the image title */
  profileName?: string;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export default function DomeExport({ svgRef, profileName = 'Profile' }: DomeExportProps) {
  const [exporting, setExporting] = useState(false);
  const [copied, setCopied] = useState(false);

  // ---- Export as PNG ----
  const handleExport = useCallback(async () => {
    if (!svgRef.current) return;
    setExporting(true);

    try {
      const svg = svgRef.current;
      const svgData = new XMLSerializer().serializeToString(svg);
      const svgBlob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' });
      const url = URL.createObjectURL(svgBlob);

      const img = new Image();
      img.onload = () => {
        // Create canvas with extra space for watermark
        const padding = 60;
        const canvas = document.createElement('canvas');
        const scale = 2; // Retina quality
        canvas.width = (img.width + padding * 2) * scale;
        canvas.height = (img.height + padding + 80) * scale; // extra for header/footer
        const ctx = canvas.getContext('2d')!;
        ctx.scale(scale, scale);

        // White background
        ctx.fillStyle = '#ffffff';
        ctx.fillRect(0, 0, canvas.width / scale, canvas.height / scale);

        // Title
        ctx.fillStyle = '#000000';
        ctx.font = "bold 18px 'Crimson Text', Georgia, serif";
        ctx.textAlign = 'center';
        ctx.fillText(
          `DOMES: ${profileName}`,
          (img.width + padding * 2) / 2,
          32,
        );

        // Date
        ctx.fillStyle = '#666666';
        ctx.font = "11px 'JetBrains Mono', monospace";
        ctx.fillText(
          new Date().toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
          }),
          (img.width + padding * 2) / 2,
          50,
        );

        // Draw SVG image
        ctx.drawImage(img, padding, 60);

        // Watermark footer
        const footerY = img.height + 60 + 30;
        ctx.fillStyle = '#aaaaaa';
        ctx.font = "9px 'JetBrains Mono', monospace";
        ctx.textAlign = 'center';
        ctx.fillText(
          'Generated by DOMES -- Data-Oriented Mapping of Entangled Systems',
          (img.width + padding * 2) / 2,
          footerY,
        );

        // Download
        canvas.toBlob((blob) => {
          if (!blob) return;
          const a = document.createElement('a');
          a.href = URL.createObjectURL(blob);
          a.download = `domes-${profileName.toLowerCase().replace(/\s+/g, '-')}-${Date.now()}.png`;
          document.body.appendChild(a);
          a.click();
          document.body.removeChild(a);
          URL.revokeObjectURL(a.href);
          setExporting(false);
        }, 'image/png');

        URL.revokeObjectURL(url);
      };

      img.onerror = () => {
        console.error('Failed to load SVG for export');
        setExporting(false);
        URL.revokeObjectURL(url);
      };

      img.src = url;
    } catch (err) {
      console.error('Export failed:', err);
      setExporting(false);
    }
  }, [svgRef, profileName]);

  // ---- Copy link ----
  const handleCopyLink = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(window.location.href);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback
      const textarea = document.createElement('textarea');
      textarea.value = window.location.href;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, []);

  return (
    <div className="flex items-center gap-2">
      <button
        onClick={handleExport}
        disabled={exporting}
        className="px-3 py-1.5 text-xs border border-black bg-white text-black hover:bg-black hover:text-white transition-colors duration-200 disabled:opacity-50"
        style={{ fontFamily: "'JetBrains Mono', monospace" }}
      >
        {exporting ? 'EXPORTING...' : 'EXPORT PNG'}
      </button>

      <button
        onClick={handleCopyLink}
        className="px-3 py-1.5 text-xs border border-black bg-white text-black hover:bg-black hover:text-white transition-colors duration-200"
        style={{ fontFamily: "'JetBrains Mono', monospace" }}
      >
        {copied ? 'COPIED!' : 'COPY LINK'}
      </button>
    </div>
  );
}
