"""
Chron Talent Agent — Seed Data
Roster of practitioners, principals, project sources
"""

from models import (
    TalentProfile, Principal, WorkItem, ProjectBrief,
    CharacterBrief, ParcelBrief, GameType, Availability,
    ProjectStatus
)


# ═══════════════════════════════════════════════════════════════════
# TALENT ROSTER — profiled by practice, not role
# ═══════════════════════════════════════════════════════════════════

SEED_TALENT = [
    TalentProfile(
        talent_id="talent-001",
        name="Elena Vasquez",
        bio="Architect who designs transitional housing. Spent 12 years studying how physical space encodes dignity — ceiling heights, natural light paths, threshold design. Every door she draws is a decision about who gets to feel at home.",
        body_of_work=[
            WorkItem(title="Threshold Housing Prototypes", description="Series of transitional housing units where every design choice maps to a dignity metric", year=2021, medium="architecture"),
            WorkItem(title="The Doorway Papers", description="Research on how entrance design affects residents' sense of belonging", year=2019, medium="research paper"),
            WorkItem(title="Bridge House", description="Mixed-use shelter redesign in Portland that reduced recidivism among residents by 34%", year=2023, medium="building"),
        ],
        domains_of_practice=["transitional housing", "spatial dignity", "threshold design", "trauma-informed architecture"],
        approach="Believes every architectural decision is a statement about who deserves beauty. Designs from the inside out — starts with how a person wakes up, not how a building looks from the street.",
        capabilities=["dome structure design", "spatial dignity assessment", "housing coordination models", "built environment as care"],
        resonance_tags=["housing", "dignity", "built-environment", "transition", "shelter", "autonomy", "care"],
    ),
    TalentProfile(
        talent_id="talent-002",
        name="Marcus Chen-Walters",
        bio="Fashion designer who spent a decade on adaptive clothing. Understands the body as a system — range of motion, sensory processing, temperature regulation, self-image. His garments are interfaces between a person and their environment.",
        body_of_work=[
            WorkItem(title="Second Skin Collection", description="Adaptive clothing line for people with limited mobility that looks like high fashion", year=2022, medium="fashion"),
            WorkItem(title="Sensory Mapping Project", description="Database of how 200+ fabrics interact with different sensory processing profiles", year=2020, medium="research"),
            WorkItem(title="Dignity Wears", description="Workwear line designed for formerly incarcerated people re-entering the workforce", year=2024, medium="fashion"),
        ],
        domains_of_practice=["adaptive fashion", "body-as-system", "sensory design", "identity through clothing"],
        approach="Clothing is the first architecture a person inhabits. Before the room, before the building — there's what touches your skin. Designs for the full sensory experience of wearing, not just the visual.",
        capabilities=["identity system design", "sensory environment assessment", "dignity through material", "body-environment interface"],
        resonance_tags=["fashion", "dignity", "body", "sensory", "identity", "adaptive", "material"],
    ),
    TalentProfile(
        talent_id="talent-003",
        name="Amara Okafor",
        bio="Chef who ran community kitchens in food deserts for 8 years. Knows what nourishment means beyond calories — it's gathering, ritual, season, memory, agency. Built a network of community kitchens that function as social infrastructure.",
        body_of_work=[
            WorkItem(title="Roots Kitchen Network", description="7 community kitchens across South Side Chicago functioning as neighborhood living rooms", year=2022, medium="social enterprise"),
            WorkItem(title="The Nourishment Index", description="Framework measuring food access across 12 dimensions beyond caloric availability", year=2021, medium="research"),
            WorkItem(title="Season Tables", description="Cookbook and social practice guide connecting seasonal eating to community gathering rhythms", year=2023, medium="book"),
        ],
        domains_of_practice=["community nutrition", "food as social infrastructure", "nourishment design", "gathering architecture"],
        approach="A kitchen is the most honest room in any building. Who cooks, who eats, who cleans up — that's the real power structure. Designs food systems that redistribute agency, not just calories.",
        capabilities=["community needs assessment", "social infrastructure design", "nourishment modeling", "gathering space activation"],
        resonance_tags=["food", "community", "gathering", "nourishment", "social-infrastructure", "agency", "neighborhood"],
    ),
    TalentProfile(
        talent_id="talent-004",
        name="Dr. Kenji Nakamura",
        bio="Data scientist who mapped hospital readmission patterns across 340 hospitals over 6 years. Sees systems as feedback loops — where the output of one failure becomes the input of the next. Built models that predict cascade failures in social safety nets.",
        body_of_work=[
            WorkItem(title="Cascade: Hospital Readmission Feedback Loops", description="6-year longitudinal study revealing how single-system failures propagate across healthcare, housing, and income", year=2023, medium="research"),
            WorkItem(title="The Fragmentation Index", description="Open-source model quantifying the cost of non-coordination across government programs", year=2022, medium="software"),
            WorkItem(title="Systems Failure Atlas", description="Interactive visualization of how 47 federal programs interact (or fail to) around a single person", year=2024, medium="data visualization"),
        ],
        domains_of_practice=["systems modeling", "cascade failure analysis", "feedback loop identification", "fragmentation quantification"],
        approach="Every system failure has a signature — a pattern of cascading consequences that you can map, model, and predict. The question isn't why systems fail, it's why we keep designing systems that are meant to fail in isolation.",
        capabilities=["cost modeling", "systems mapping", "data integration", "fragmentation analysis", "feedback loop detection"],
        resonance_tags=["data", "systems", "feedback-loops", "fragmentation", "cost", "modeling", "healthcare", "cascade"],
    ),
    TalentProfile(
        talent_id="talent-005",
        name="Simone Deveraux",
        bio="Poet who documented incarceration through letters — 4 years collecting, curating, and amplifying correspondence between incarcerated people and their families. Understands narrative as survival, language as lifeline, documentation as resistance.",
        body_of_work=[
            WorkItem(title="Letters from the Inside", description="Collection of 600+ letters between incarcerated parents and their children, curated as an archive of resilience", year=2021, medium="book"),
            WorkItem(title="The Waiting Room", description="Immersive poetry installation recreating the sensory experience of visiting someone in prison", year=2022, medium="installation"),
            WorkItem(title="Sentence Structure", description="Documentary poetry series mapping how legal language shapes lived experience", year=2023, medium="poetry"),
        ],
        domains_of_practice=["documentary poetry", "incarceration narratives", "language as resistance", "family documentation"],
        approach="Every bureaucratic form has a human story compressed into its checkboxes. Her work expands what gets compressed — finds the person inside the case number, the family inside the file.",
        capabilities=["narrative construction", "human story extraction", "documentation as care", "voice amplification"],
        resonance_tags=["narrative", "incarceration", "family", "documentation", "language", "voice", "justice", "storytelling"],
    ),
    TalentProfile(
        talent_id="talent-006",
        name="David Oyelaran",
        bio="Financial engineer who structured microfinance products in 6 developing economies. Understands how capital flows shape who gets to participate in their own future. Built instruments that make invisible value visible and investable.",
        body_of_work=[
            WorkItem(title="Participation Bonds", description="Bond structure that converts community engagement metrics into investable returns", year=2022, medium="financial product"),
            WorkItem(title="The Invisible Ledger", description="Research on how informal economies create value that formal finance can't see", year=2020, medium="research"),
            WorkItem(title="Micro-Impact Securities", description="Portfolio of microfinance instruments across 6 countries with 12% average returns and 94% repayment", year=2023, medium="financial product"),
        ],
        domains_of_practice=["microfinance", "impact investing", "invisible value instruments", "community capital"],
        approach="Finance is a language. Most people are forced to speak it without ever being taught. Designs instruments that translate community value into financial terms without losing what makes it valuable.",
        capabilities=["bond pricing", "financial instrument design", "impact quantification", "capital structure"],
        resonance_tags=["finance", "bonds", "microfinance", "impact", "community-capital", "instruments", "value"],
    ),
    TalentProfile(
        talent_id="talent-007",
        name="Iris Konstantinidou",
        bio="Choreographer who works with elderly populations. Thinks about movement as autonomy — the difference between being moved and moving yourself. Created movement programs in 15 care facilities that reduced falls by 40% and depression scores by 60%.",
        body_of_work=[
            WorkItem(title="Still Moving", description="Movement program for care facilities that reframes physical therapy as creative practice", year=2021, medium="program"),
            WorkItem(title="The Autonomy of Gesture", description="Research on how self-directed movement affects wellbeing in institutional settings", year=2022, medium="research"),
            WorkItem(title="Threshold Dances", description="Performance series where elderly residents choreograph the movements of their daily transitions — waking, eating, resting", year=2023, medium="performance"),
        ],
        domains_of_practice=["movement as autonomy", "elderly care", "embodied wellbeing", "institutional transformation through dance"],
        approach="Autonomy begins in the body. Before choice, before voice — there's the ability to move yourself. Every institution that moves people without asking is practicing a form of control. Her work returns movement to the person.",
        capabilities=["wellbeing assessment through movement", "autonomy metrics", "institutional care transformation", "embodied dignity"],
        resonance_tags=["movement", "autonomy", "elderly", "care", "body", "wellbeing", "institutional", "dance"],
    ),
    TalentProfile(
        talent_id="talent-008",
        name="Theo Park",
        bio="Game designer who built accessibility features for 3 major studios. Understands friction as a design choice — every barrier in a system is either protecting someone or excluding them, and most systems can't tell the difference.",
        body_of_work=[
            WorkItem(title="Universal Play Framework", description="Accessibility framework adopted by 3 major game studios, used in 40+ titles", year=2022, medium="software"),
            WorkItem(title="Friction Mapping", description="Tool that audits any digital system for unnecessary barriers vs. necessary friction", year=2023, medium="software"),
            WorkItem(title="The Barrier Atlas", description="Interactive map of accessibility barriers in government benefit applications", year=2024, medium="data visualization"),
        ],
        domains_of_practice=["accessibility design", "friction analysis", "barrier mapping", "inclusive systems"],
        approach="Every form, every portal, every waiting room is a game with hidden rules. Some friction protects you (confirming a medical decision). Most friction excludes you (requiring a fax machine in 2024). His work makes the rules visible.",
        capabilities=["system friction analysis", "accessibility auditing", "barrier identification", "inclusive design"],
        resonance_tags=["accessibility", "friction", "barriers", "systems", "inclusion", "design", "government", "digital"],
    ),
    TalentProfile(
        talent_id="talent-009",
        name="Ruth Abernathy",
        bio="Nurse practitioner who ran a mobile clinic in rural Appalachia for 11 years. Understands healthcare as presence — showing up where people are, not making them come to where care is. Her clinic served 3,200 patients across 7 counties.",
        body_of_work=[
            WorkItem(title="The Mountain Circuit", description="Mobile clinic network serving 7 Appalachian counties, 3,200 patients, 11 years running", year=2023, medium="healthcare practice"),
            WorkItem(title="Proximity Medicine", description="Research framework on how physical distance to care correlates with health outcomes in rural populations", year=2021, medium="research"),
            WorkItem(title="The Trust Protocol", description="Training curriculum for building clinical trust in communities with deep institutional distrust", year=2022, medium="curriculum"),
        ],
        domains_of_practice=["mobile healthcare", "rural medicine", "trust-based care", "proximity as care model"],
        approach="Healthcare isn't a building. It's a relationship. The most advanced medical system in the world is useless if the patient can't get there, can't afford it, or doesn't trust it. Her work eliminates the distance.",
        capabilities=["healthcare access modeling", "trust building", "mobile service design", "rural needs assessment"],
        resonance_tags=["healthcare", "rural", "mobile", "trust", "proximity", "access", "care", "community"],
    ),
    TalentProfile(
        talent_id="talent-010",
        name="Santiago Reyes-Moreno",
        bio="Landscape architect who converted 14 brownfields into community gardens. Knows soil literally and metaphorically — what's underneath, what's contaminated, what can grow. His sites generate $2.3M in annual community food production.",
        body_of_work=[
            WorkItem(title="Remediation Gardens", description="14 brownfield-to-garden conversions across 3 cities, $2.3M annual food production", year=2023, medium="landscape architecture"),
            WorkItem(title="Soil Memory", description="Research on how industrial contamination histories affect community relationships to land", year=2020, medium="research"),
            WorkItem(title="The Growth Protocol", description="Open-source methodology for converting contaminated urban lots to productive community space in 18 months", year=2022, medium="methodology"),
        ],
        domains_of_practice=["brownfield remediation", "community gardens", "soil science", "land transformation"],
        approach="Every vacant lot has a memory in its soil. You can't just plant — you have to understand what happened there, who was harmed, what was produced, what remains. Transformation starts underground.",
        capabilities=["site assessment", "remediation planning", "community food systems", "land transformation methodology"],
        resonance_tags=["landscape", "soil", "brownfield", "garden", "community", "food", "land", "transformation", "space"],
    ),
    TalentProfile(
        talent_id="talent-011",
        name="Khadija Al-Rashid",
        bio="Industrial designer who prototyped affordable prosthetics using locally sourced materials. Built 340 functional limbs at 1/50th the cost of commercial alternatives. Understands that good design means nothing if nobody can afford it.",
        body_of_work=[
            WorkItem(title="Open Limb Project", description="Open-source prosthetic designs using locally sourced materials, 340 units deployed in 4 countries", year=2022, medium="product design"),
            WorkItem(title="The Affordability Equation", description="Research on how design complexity correlates with cost barriers in assistive technology", year=2021, medium="research"),
            WorkItem(title="Material Substitution Atlas", description="Database of 200+ material substitutions that maintain function while reducing cost by 80%+", year=2023, medium="database"),
        ],
        domains_of_practice=["affordable design", "prosthetics", "material innovation", "assistive technology"],
        approach="Luxury is easy. Constraint is where design actually happens. When you have $50 instead of $5,000, every material choice becomes an act of respect for who's going to use it.",
        capabilities=["affordable fabrication", "material innovation", "assistive device design", "cost-constrained engineering"],
        resonance_tags=["industrial-design", "prosthetics", "affordable", "material", "assistive", "fabrication", "constraint"],
    ),
    TalentProfile(
        talent_id="talent-012",
        name="Jerome Osei",
        bio="Musician who built sound therapy programs in 4 psychiatric facilities. Understands that sound shapes cognitive state before conscious thought — the hum of fluorescent lights, the echo of hallways, the silence of isolation. Redesigned sonic environments for healing.",
        body_of_work=[
            WorkItem(title="Sonic Healing Environments", description="Sound design interventions in 4 psychiatric facilities reducing agitation incidents by 45%", year=2022, medium="sound design"),
            WorkItem(title="The Frequency of Calm", description="Research on how ambient sound frequencies affect psychiatric patient outcomes", year=2021, medium="research"),
            WorkItem(title="Institutional Soundscapes", description="Album of field recordings from care facilities with sound design interventions overlaid", year=2023, medium="music"),
        ],
        domains_of_practice=["sound therapy", "sonic environment design", "psychiatric care", "ambient healing"],
        approach="Every institution has a sound. Most institutional sounds tell you that you don't matter — the buzzer, the PA, the fluorescent hum. His work replaces those sounds with ones that say you're safe here.",
        capabilities=["sonic environment assessment", "sound-based wellbeing", "institutional environment design", "healing soundscape creation"],
        resonance_tags=["sound", "music", "therapy", "healing", "environment", "psychiatric", "institutional", "ambient"],
    ),
    TalentProfile(
        talent_id="talent-013",
        name="Patricia Hawkins-Morrow",
        bio="Constitutional lawyer who litigated disability rights cases for 18 years. Won 23 landmark cases. Understands rights not as abstractions but as architectures — every right is a structure that either holds or collapses under pressure.",
        body_of_work=[
            WorkItem(title="23 Landmark Disability Rights Cases", description="18-year litigation practice establishing precedents in ADA, IDEA, and Section 504 enforcement", year=2024, medium="legal practice"),
            WorkItem(title="The Architecture of Rights", description="Book analyzing how legal entitlements function as structural supports or structural failures", year=2022, medium="book"),
            WorkItem(title="Rights Gap Analysis Tool", description="Open-source tool for identifying gaps between legal entitlements and actual access", year=2023, medium="software"),
        ],
        domains_of_practice=["disability rights", "constitutional law", "rights architecture", "entitlement enforcement"],
        approach="A right on paper and a right in practice are two different buildings. Her work measures the gap between them — and builds bridges where the distance is greatest.",
        capabilities=["legal landscape mapping", "rights gap analysis", "entitlement research", "legal architecture design"],
        resonance_tags=["law", "rights", "disability", "entitlement", "constitution", "legal", "enforcement", "gap-analysis"],
    ),
    TalentProfile(
        talent_id="talent-014",
        name="Andre Washington",
        bio="Filmmaker who made 6 documentaries about housing courts. Spent 3 years in eviction proceedings filming what the system looks like from the defendant's chair. His work has been cited in 4 legislative hearings.",
        body_of_work=[
            WorkItem(title="Docket", description="Feature documentary on eviction courts, premiered at Sundance, cited in 4 legislative hearings", year=2022, medium="film"),
            WorkItem(title="The Other Side of the Bench", description="Docuseries following judges, tenants, and landlords through the same proceedings", year=2023, medium="film"),
            WorkItem(title="Courtroom Portraits", description="Photography series documenting the physical spaces of housing justice", year=2021, medium="photography"),
        ],
        domains_of_practice=["documentary filmmaking", "housing justice", "courtroom documentation", "systemic storytelling"],
        approach="The camera doesn't have an opinion, but it has a position. Where you place it changes everything. His camera sits where the defendant sits — facing the system, not observing it.",
        capabilities=["documentary production", "systemic storytelling", "visual documentation", "narrative construction"],
        resonance_tags=["film", "documentary", "housing", "justice", "eviction", "courts", "storytelling", "visual"],
    ),
    TalentProfile(
        talent_id="talent-015",
        name="Maya Patel",
        bio="Software engineer who built open-source benefits calculators used by 2M+ people annually. Understands that the interface between a person and their government benefits is itself a form of policy — complexity is a feature, not a bug.",
        body_of_work=[
            WorkItem(title="BenefitsEngine", description="Open-source benefits calculator serving 2M+ annual users across 12 states", year=2023, medium="software"),
            WorkItem(title="The Complexity Tax", description="Research quantifying the hours Americans spend navigating benefit applications", year=2022, medium="research"),
            WorkItem(title="SimpleGov API", description="API layer that normalizes 47 different government benefit application formats into one interface", year=2024, medium="software"),
        ],
        domains_of_practice=["government technology", "benefits access", "interface as policy", "complexity reduction"],
        approach="Every dropdown menu in a government form is a policy decision. Every error message is an access barrier. Her work treats user interfaces as civil rights infrastructure.",
        capabilities=["government API integration", "benefits modeling", "system interconnection", "complexity analysis"],
        resonance_tags=["software", "government", "benefits", "API", "interface", "access", "technology", "systems"],
    ),
    TalentProfile(
        talent_id="talent-016",
        name="Dr. Nadia Okonkwo",
        bio="Sociologist who studied how families navigate bureaucracies for 9 years. Followed 60 families through their interactions with government systems. Documented the invisible labor of being poor — the hours, the forms, the waiting, the explaining.",
        body_of_work=[
            WorkItem(title="The Navigation Tax", description="9-year ethnography of 60 families navigating government benefits systems", year=2023, medium="research"),
            WorkItem(title="Bureaucratic Cartography", description="Methodology for mapping the actual paths families take through government systems vs. intended paths", year=2021, medium="research methodology"),
            WorkItem(title="The Waiting Room Index", description="Quantification of the economic cost of time spent waiting for government services", year=2022, medium="research"),
        ],
        domains_of_practice=["bureaucratic navigation", "poverty ethnography", "systems anthropology", "invisible labor documentation"],
        approach="The system works exactly as designed. It's designed to be navigable only by people who have time, literacy, transportation, childcare, and the emotional energy to try again when it fails. Her work makes the design visible.",
        capabilities=["system navigation mapping", "family impact assessment", "bureaucratic cost analysis", "ethnographic research"],
        resonance_tags=["sociology", "bureaucracy", "families", "navigation", "poverty", "systems", "labor", "waiting"],
    ),
    TalentProfile(
        talent_id="talent-017",
        name="Rio Tanaka",
        bio="Graphic novelist who illustrated the foster care system across 3 books. Made the invisible visible — the file folders, the case numbers, the car rides between placements, the garbage bags instead of suitcases.",
        body_of_work=[
            WorkItem(title="Case Number Trilogy", description="Three graphic novels following different children through foster care — from entry to aging out", year=2023, medium="graphic novel"),
            WorkItem(title="The File", description="Visual essay showing what a child looks like as a case file vs. as a person", year=2021, medium="illustration"),
            WorkItem(title="Placement Maps", description="Illustrated maps showing the geographic journeys of foster children across placements", year=2022, medium="illustration"),
        ],
        domains_of_practice=["graphic narrative", "foster care documentation", "visual systems critique", "childhood justice"],
        approach="A system that processes 400,000 children a year has a visual language — forms, databases, van schedules, court dockets. His work draws the system from the child's height, at the child's reading level, in the child's emotional register.",
        capabilities=["visual storytelling", "system visualization", "emotional architecture", "child-centered documentation"],
        resonance_tags=["graphic-novel", "foster-care", "illustration", "children", "visualization", "justice", "narrative"],
    ),
    TalentProfile(
        talent_id="talent-018",
        name="Celeste Dubois",
        bio="Perfumer who understands how environment shapes wellbeing. Spent 6 years studying the olfactory experience of institutional spaces — hospitals, shelters, courtrooms. Created scent interventions that measurably reduce stress and increase sense of safety.",
        body_of_work=[
            WorkItem(title="Institutional Olfactory Audit", description="6-year study of how institutional smells affect patient/resident stress and recovery", year=2022, medium="research"),
            WorkItem(title="Safe Scent Protocol", description="Scent intervention system for shelters and hospitals, reducing cortisol levels by 28%", year=2023, medium="product"),
            WorkItem(title="The Smell of Home", description="Personalized scent profiles for institutional residents based on comfort memory mapping", year=2024, medium="product"),
        ],
        domains_of_practice=["olfactory design", "environmental wellbeing", "institutional sensory experience", "scent as care"],
        approach="Every institution smells like control — bleach, floor wax, recycled air. That smell tells your nervous system you're not safe before your brain catches up. Her work designs what safety smells like.",
        capabilities=["environmental wellbeing assessment", "sensory care design", "institutional environment transformation", "stress reduction"],
        resonance_tags=["scent", "environment", "wellbeing", "institutional", "sensory", "safety", "care", "perfume"],
    ),
    TalentProfile(
        talent_id="talent-019",
        name="James Ironheart",
        bio="Blacksmith who understands material transformation and permanent making. Runs a forge that trains formerly incarcerated people. The act of taking raw iron and making something permanent, beautiful, and functional is the whole metaphor — and also the whole job training program.",
        body_of_work=[
            WorkItem(title="Forge Forward", description="Job training program teaching blacksmithing to formerly incarcerated people, 89% employment rate", year=2022, medium="program"),
            WorkItem(title="Public Works", description="Series of permanent public art installations made by program graduates", year=2023, medium="sculpture"),
            WorkItem(title="The Transformation Papers", description="Research on how material transformation practices affect personal transformation outcomes", year=2021, medium="research"),
        ],
        domains_of_practice=["material transformation", "permanent making", "reentry employment", "craft as rehabilitation"],
        approach="Iron doesn't lie. You either shaped it right or you didn't. There's no performance review, no recidivism metric — there's a gate hinge that works or doesn't. His work uses material honesty as the foundation for personal transformation.",
        capabilities=["permanent fabrication", "material transformation", "workforce development", "public art installation"],
        resonance_tags=["blacksmith", "forge", "material", "transformation", "reentry", "permanent", "craft", "public-art"],
    ),
    TalentProfile(
        talent_id="talent-020",
        name="Comfort Adeyemi",
        bio="Midwife who understands transition, vulnerability, and support. Practiced in both hospital and home settings. Sees every system transition — leaving prison, entering shelter, starting benefits — as a kind of birth: terrifying, transformative, and requiring skilled presence.",
        body_of_work=[
            WorkItem(title="Transition Frameworks", description="Training program applying midwifery principles to social service transitions", year=2022, medium="curriculum"),
            WorkItem(title="The Birth Parallel", description="Research mapping structural similarities between childbirth support and system-transition support", year=2021, medium="research"),
            WorkItem(title="Presence Protocol", description="Model for accompaniment-based social services, piloted in 3 reentry programs", year=2023, medium="program"),
        ],
        domains_of_practice=["transition support", "accompaniment models", "vulnerability frameworks", "presence-based care"],
        approach="Every major life transition has the same structure: you can't go back, you can't see what's ahead, and you need someone who's been there to tell you you're going to be okay. Her work builds that presence into every system transition.",
        capabilities=["transition modeling", "accompaniment design", "vulnerability assessment", "support structure architecture"],
        resonance_tags=["midwife", "transition", "vulnerability", "support", "presence", "accompaniment", "care", "birth"],
    ),
    TalentProfile(
        talent_id="talent-021",
        name="Zara Kalil",
        bio="Graffiti artist who understands public space as canvas. 20 years of large-scale murals in neighborhoods where public art budgets don't exist. Her walls tell the stories that official histories leave out.",
        body_of_work=[
            WorkItem(title="The Unofficial History Project", description="40+ large-scale murals documenting community histories in neighborhoods facing gentrification", year=2023, medium="mural"),
            WorkItem(title="Wall Rights", description="Legal advocacy for artists' rights to public expression, established precedent in 3 cities", year=2022, medium="legal advocacy"),
            WorkItem(title="Canvas City", description="Training program teaching large-scale mural technique to community youth, 200+ graduates", year=2024, medium="program"),
        ],
        domains_of_practice=["public art", "community documentation", "large-scale mural", "space as expression"],
        approach="A wall is either talking or it's silent. Silent walls in a neighborhood mean nobody thinks the people who live there have anything worth saying. Her work makes walls speak in the voice of the community.",
        capabilities=["public space activation", "community voice amplification", "large-scale visual storytelling", "space transformation"],
        resonance_tags=["graffiti", "mural", "public-space", "community", "art", "expression", "walls", "neighborhood"],
    ),
]


# ═══════════════════════════════════════════════════════════════════
# PRINCIPALS — top-tier production leaders
# ═══════════════════════════════════════════════════════════════════

SEED_PRINCIPALS = [
    Principal(
        principal_id="principal-001",
        name="Ryan Coogler",
        bio="World-building rooted in real communities. Cultural specificity as structural element. Makes systemic injustice visceral without being reductive.",
        vision="His dome productions would feel like Wakanda inverted — not a fantasy of what could be, but a blueprint built from what actually exists in the legal code, made visible for the first time.",
        game_type=GameType.DOMES,
        body_of_work=[
            WorkItem(title="Fruitvale Station", description="True story of Oscar Grant, system failure made intimate", year=2013, medium="film"),
            WorkItem(title="Black Panther", description="World-building that treats African diaspora culture as technological foundation", year=2018, medium="film"),
            WorkItem(title="Creed Series", description="Legacy, transformation, and what gets inherited from broken systems", year=2015, medium="film"),
        ],
        signature_style="Community-rooted world-building. Every systemic truth grounded in one person's story. Technology serving culture, not replacing it.",
    ),
    Principal(
        principal_id="principal-002",
        name="Jonathan Nolan",
        bio="Systems thinking, nonlinear architecture, the obsession with how information structures shape human experience.",
        vision="His dome productions would expose the algorithmic logic of government fragmentation — the nested loops, the recursive failures, the emergent patterns nobody designed but everyone suffers.",
        game_type=GameType.DOMES,
        body_of_work=[
            WorkItem(title="Westworld", description="Systems that process humans, the architecture of consciousness and control", year=2016, medium="television"),
            WorkItem(title="Person of Interest", description="Surveillance, predictive systems, the ethics of algorithmic governance", year=2011, medium="television"),
            WorkItem(title="The Prestige", description="Obsession, duplication, the cost of seeing how the trick works", year=2006, medium="film"),
        ],
        signature_style="Nonlinear systems architecture. Information as character. The moment when the pattern becomes visible and you realize it was always there.",
    ),
    Principal(
        principal_id="principal-003",
        name="Ava DuVernay",
        bio="The intersection of justice systems and human dignity. Institutional critique as narrative form. Never loses sight of the individual inside the structure.",
        vision="Her dome productions would center the person's experience of being inside the system looking out — the paperwork, the waiting, the explaining yourself again, the moment when coordination actually works.",
        game_type=GameType.DOMES,
        body_of_work=[
            WorkItem(title="13th", description="Constitutional amendment to mass incarceration — the system made visible", year=2016, medium="documentary"),
            WorkItem(title="When They See Us", description="Five boys inside a justice system designed to process them, not see them", year=2019, medium="television"),
            WorkItem(title="Selma", description="Structural power vs. organized resistance, the mechanics of change", year=2014, medium="film"),
        ],
        signature_style="Individual dignity within structural critique. The person is never an example — they're the protagonist. The system is the antagonist, not the subject.",
    ),
    Principal(
        principal_id="principal-004",
        name="James Cameron",
        bio="Engineering-scale ambition. Builds entirely new tools to realize a vision. Integration of technology and storytelling at a level nobody else attempts.",
        vision="His dome productions would push the visualization and simulation technology — the dome as a living, stress-testable digital twin of a human life. You could model 10 years of a person's trajectory under different coordination scenarios.",
        game_type=GameType.DOMES,
        body_of_work=[
            WorkItem(title="Avatar", description="World-building at planetary scale, technology serving biology", year=2009, medium="film"),
            WorkItem(title="Titanic", description="Class architecture as literal architecture — the ship as social system", year=1997, medium="film"),
            WorkItem(title="The Abyss", description="Extreme environments, the technology required to survive in systems not designed for humans", year=1989, medium="film"),
        ],
        signature_style="Build the tools first, then build the world. Engineering rigor in service of emotional truth. If the simulation doesn't hold, the story doesn't hold.",
    ),
    Principal(
        principal_id="principal-005",
        name="Bong Joon-ho",
        bio="Class architecture as spatial design. Physical spaces that encode economic relationships. Dark comedy as truth-telling.",
        vision="His dome productions would make the absurdity of fragmentation undeniable — funny and devastating simultaneously. The person navigating 14 disconnected benefit systems as a Kafka comedy that suddenly isn't funny anymore.",
        game_type=GameType.DOMES,
        body_of_work=[
            WorkItem(title="Parasite", description="Class encoded in architecture — who lives above, who lives below, and the stairs between", year=2019, medium="film"),
            WorkItem(title="Snowpiercer", description="Social systems as literal train cars — position is destiny", year=2013, medium="film"),
            WorkItem(title="Okja", description="Industrial systems that process living beings, the absurdity of scale", year=2017, medium="film"),
        ],
        signature_style="Architecture as class critique. Space reveals truth. Comedy and tragedy occupying the same frame. The moment when the system's design becomes physically visible.",
    ),
    # SPHERES PRINCIPALS
    Principal(
        principal_id="principal-006",
        name="Populous Design Group",
        bio="Stadium architects. The science of crowd flow, sight lines, acoustic design, the engineering of collective experience at scale.",
        vision="They treat a vacant lot with the same rigor they bring to a 70,000-seat stadium — flow analysis, acoustic modeling, sight lines, the choreography of arrival and departure. Every activation is engineered for collective experience.",
        game_type=GameType.SPHERES,
        body_of_work=[
            WorkItem(title="Tottenham Hotspur Stadium", description="Multi-use venue engineering — the same space serves football, NFL, concerts, community", year=2019, medium="architecture"),
            WorkItem(title="Climate Pledge Arena", description="Zero-carbon arena, the engineering of sustainable collective experience", year=2021, medium="architecture"),
            WorkItem(title="SoFi Stadium", description="Open-air engineering that creates enclosure without walls", year=2020, medium="architecture"),
        ],
        signature_style="Engineering rigor for collective experience. Every square meter has a purpose, a flow, a sight line. The crowd is the material — the building shapes how they move, see, hear, and feel together.",
    ),
    Principal(
        principal_id="principal-007",
        name="Roc Nation Productions",
        bio="Super Bowl halftime-level production. The compression of spectacle into minutes. Transforming a space completely and returning it. Dozens of creative disciplines under extreme time pressure.",
        vision="Every vacant lot activation gets the halftime treatment — the logistics of total space transformation, the coordination of dozens of creative disciplines, the spectacle that draws attention and the infrastructure that makes it sustainable.",
        game_type=GameType.SPHERES,
        body_of_work=[
            WorkItem(title="Super Bowl Halftime Shows", description="The coordination of 600+ performers, technical crew, and creative teams in a 13-minute window", year=2023, medium="live production"),
            WorkItem(title="Made in America Festival", description="Multi-day urban festival that transforms Benjamin Franklin Parkway into a cultural city", year=2022, medium="festival"),
            WorkItem(title="Roc Nation Brunch", description="The compression of cultural significance into a single curated event", year=2023, medium="event"),
        ],
        signature_style="Spectacle with infrastructure. The show draws the attention, the organization underneath makes it repeatable. Every event leaves the space better than it found it.",
    ),
    Principal(
        principal_id="principal-008",
        name="Meow Wolf Collective",
        bio="The transformation of dead space into living world. Multi-sensory immersive environments where participants discover the space rather than being told about it.",
        vision="Every vacant lot becomes a portal — not a park, not a plaza, but a world. The activation doesn't decorate the space, it transforms what the space IS. Participants don't visit, they explore.",
        game_type=GameType.SPHERES,
        body_of_work=[
            WorkItem(title="House of Eternal Return", description="Converted bowling alley into permanent multidimensional narrative — 40+ rooms, each a different world", year=2016, medium="immersive art"),
            WorkItem(title="Omega Mart", description="Grocery store as portal to alternate dimension — commercial space subverted into art", year=2021, medium="immersive art"),
            WorkItem(title="The Real Unreal", description="The convergence of physical space and digital narrative — reality as a design material", year=2023, medium="immersive art"),
        ],
        signature_style="Dead space into living world. Every surface is interactive. The audience discovers the narrative by moving through the space. Disorientation as invitation.",
    ),
    Principal(
        principal_id="principal-009",
        name="James Corner / Field Operations",
        bio="The transformation of infrastructure into public life. Long-term ecological thinking. The negotiation between nature and city.",
        vision="Every vacant lot is infrastructure waiting to become public life. The activation isn't temporary — it's the first phase of a 30-year ecological and social transformation. The lot becomes a park that becomes a neighborhood anchor.",
        game_type=GameType.SPHERES,
        body_of_work=[
            WorkItem(title="The High Line", description="Abandoned rail infrastructure transformed into linear park — the template for urban reclamation", year=2009, medium="landscape architecture"),
            WorkItem(title="Domino Park", description="Former sugar refinery waterfront transformed into community green space", year=2018, medium="landscape architecture"),
            WorkItem(title="Freshkills Park", description="Former landfill being transformed into NYC's largest park — infrastructure as ecological redemption", year=2024, medium="landscape architecture"),
        ],
        signature_style="Infrastructure into ecology into community. 30-year vision, 30-day activation. The site's industrial history becomes its cultural identity. Nature as the most patient designer.",
    ),
    Principal(
        principal_id="principal-010",
        name="Bureau Betak / Alexandre de Betak",
        bio="Fashion show production. The choreography of attention, the sequencing of revelation, the transformation of raw space into spectacle through light, sound, and movement.",
        vision="A vacant lot activated like a runway show — every arrival is choreographed, every reveal is timed, the space is transformed not by construction but by light, sound, sequence, and attention. The ephemeral becomes permanent through the experience it creates.",
        game_type=GameType.SPHERES,
        body_of_work=[
            WorkItem(title="Dior Cruise Collections", description="Historic sites transformed into fashion spectacles — the location IS the collection", year=2023, medium="production"),
            WorkItem(title="Jacquemus Le Papier", description="Art gallery transformed into paper dreamscape — every surface reimagined", year=2022, medium="production"),
            WorkItem(title="Coperni Spray-On Dress", description="Single transformative moment that redefines what fashion presentation can be", year=2022, medium="production"),
        ],
        signature_style="Attention as material. The sequence in which things are revealed changes what they mean. Raw space is the best canvas because it has no expectations. Transformation happens in the viewer, not the space.",
    ),
    Principal(
        principal_id="principal-011",
        name="Punchdrunk / Felix Barrett",
        bio="Immersive theater. The audience as participant, the building itself as character. Narrative discovered through movement, not told through dialogue.",
        vision="Every vacant lot becomes a stage where visitors discover the story by moving through it — the parcel's history encoded in objects, sounds, textures. The activation isn't watched, it's inhabited. Sleep No More for a city block.",
        game_type=GameType.SPHERES,
        body_of_work=[
            WorkItem(title="Sleep No More", description="Immersive Macbeth across 5 floors — audience explores freely, narrative is spatial not linear", year=2011, medium="immersive theater"),
            WorkItem(title="The Drowned Man", description="Film noir in an abandoned postal sorting office — space as character, audience as detective", year=2013, medium="immersive theater"),
            WorkItem(title="The Burnt City", description="Troy and Greece across two vast warehouses — parallel civilizations explored simultaneously", year=2022, medium="immersive theater"),
        ],
        signature_style="The audience discovers the narrative by moving through the space. Every room is a scene. Every object is a prop. The building is the script. Curiosity drives the experience.",
    ),
    Principal(
        principal_id="principal-012",
        name="Local Projects / Jake Barton",
        bio="Museum exhibition design. The architecture of understanding — how to move people through information spatially, how to make complex stories physically navigable.",
        vision="Every activation is a walkable argument — the parcel's data, history, and community story rendered as a physical experience you move through. Not a sign on a vacant lot. An exhibition that IS the lot.",
        game_type=GameType.SPHERES,
        body_of_work=[
            WorkItem(title="9/11 Memorial Museum", description="Making absence present — designing how a nation processes collective trauma through space", year=2014, medium="exhibition design"),
            WorkItem(title="Cooper Hewitt Pen", description="Rethinking museum interaction — visitors design as they move through the collection", year=2015, medium="interaction design"),
            WorkItem(title="StoryCorps Installation", description="Making oral history spatial — individual voices creating collective understanding", year=2018, medium="exhibition design"),
        ],
        signature_style="Information made spatial. Data made emotional. Complex stories made physically navigable. The visitor leaves understanding something they couldn't have learned from reading.",
    ),
]


# ═══════════════════════════════════════════════════════════════════
# PROJECT SOURCES — characters (DOMES) and parcels (SPHERES)
# ═══════════════════════════════════════════════════════════════════

SEED_PROJECTS = [
    # DOMES — characters from documented sources
    ProjectBrief(
        project_id="project-001",
        game_type=GameType.DOMES,
        title="The Dasani Production",
        status=ProjectStatus.SOURCED,
        character=CharacterBrief(
            name="Dasani Coates",
            source="Invisible Child by Andrea Elliott",
            source_citation="Elliott, Andrea. Invisible Child: Poverty, Survival, and Hope in an American City. Random House, 2021.",
            situation="A child navigating homelessness in NYC, living in a shelter with her family while attending school, managing her siblings, and fighting for normalcy inside a system that processes her family as a case number.",
            full_landscape="Brilliant, creative, fiercely protective of her siblings. An athlete, a student, a daughter who carries adult weight. Her life includes not just poverty but joy, intelligence, ambition, humor, and an extraordinary ability to read systems and people.",
            production_challenge="Building a dome around a child who is simultaneously inside the shelter system, the education system, the child welfare system, and the family court system — all of which operate independently. The dome must coordinate what these systems refuse to coordinate on their own.",
            key_systems=["homeless shelter system", "public education", "child welfare", "family court", "Medicaid", "SNAP", "TANF"],
            flourishing_dimensions=["housing", "education", "family stability", "health", "creativity", "autonomy", "belonging"],
        ),
    ),
    ProjectBrief(
        project_id="project-002",
        game_type=GameType.DOMES,
        title="The Arleen Production",
        status=ProjectStatus.SOURCED,
        character=CharacterBrief(
            name="Arleen Belle",
            source="Evicted by Matthew Desmond",
            source_citation="Desmond, Matthew. Evicted: Poverty and Profit in the American City. Crown, 2016.",
            situation="A mother of two boys facing serial eviction in Milwaukee. Each eviction triggers a cascade — new school, lost job, broken social connections, deeper poverty. The eviction record itself becomes a barrier to future housing.",
            full_landscape="A mother whose primary project is keeping her family together and housed. Resourceful, strategic, deeply knowledgeable about landlord-tenant dynamics. Her 'problem' is a housing market designed to extract from her, not serve her.",
            production_challenge="The dome must address the eviction cascade — how one housing loss triggers failures across employment, education, healthcare, and social connection. The financial instruments need to make coordination cheaper than fragmentation.",
            key_systems=["housing court", "rental assistance", "public housing", "TANF", "Medicaid", "public schools", "employment services"],
            flourishing_dimensions=["housing", "employment", "education", "community", "dignity", "stability", "financial security"],
        ),
    ),
    ProjectBrief(
        project_id="project-003",
        game_type=GameType.DOMES,
        title="The DeAndre Production",
        status=ProjectStatus.SOURCED,
        character=CharacterBrief(
            name="DeAndre McCullough",
            source="The Corner by David Simon & Ed Burns",
            source_citation="Simon, David and Burns, Ed. The Corner: A Year in the Life of an Inner-City Neighborhood. Broadway Books, 1997.",
            situation="A teenager in West Baltimore navigating the drug economy, the education system, and the criminal justice system — three systems that intersect on the same street corner but never coordinate.",
            full_landscape="Intelligent, charismatic, caught between the immediate economy of the corner and the delayed promises of school. Loves his mother, understands the system better than most adults, carries the weight of decisions no teenager should face.",
            production_challenge="Three systems — education, criminal justice, and the informal economy — all claim jurisdiction over the same young person but none coordinate. The dome must make the legitimate path more accessible than the illegitimate one, starting from his actual geography.",
            key_systems=["public education", "juvenile justice", "substance abuse treatment", "Medicaid", "SNAP", "workforce development", "public housing"],
            flourishing_dimensions=["education", "employment", "health", "community", "purpose", "safety", "autonomy"],
        ),
    ),
    ProjectBrief(
        project_id="project-004",
        game_type=GameType.DOMES,
        title="The Barbara Ehrenreich Production",
        status=ProjectStatus.SOURCED,
        character=CharacterBrief(
            name="Composite: Low-Wage Worker",
            source="Nickel and Dimed by Barbara Ehrenreich",
            source_citation="Ehrenreich, Barbara. Nickel and Dimed: On (Not) Getting By in America. Holt, 2001.",
            situation="Working full-time (often multiple jobs) and still unable to afford housing, healthcare, or basic stability. The gap between wage and cost of living creates a permanent crisis that looks like individual failure but is structural design.",
            full_landscape="Hardworking, resourceful, managing logistics that would challenge an operations manager — shift schedules, transportation routes, childcare chains, benefit applications, all while working 60+ hours a week. The 'unskilled' label applied to work that requires extraordinary skill.",
            production_challenge="The dome must address the working-poor paradox — people who are fully employed but fully excluded from stability. The financial instruments need to capture the value of coordination savings for employers, municipalities, and workers simultaneously.",
            key_systems=["EITC", "Medicaid expansion", "SNAP", "Section 8", "CHIP", "workforce development", "transportation"],
            flourishing_dimensions=["income", "housing", "healthcare", "time", "dignity", "rest", "purpose"],
        ),
    ),
    ProjectBrief(
        project_id="project-005",
        game_type=GameType.DOMES,
        title="The Moonee Production",
        status=ProjectStatus.SOURCED,
        character=CharacterBrief(
            name="Moonee (Composite: Motel Child)",
            source="The Florida Project (film, Sean Baker, 2017)",
            source_citation="Baker, Sean, dir. The Florida Project. A24, 2017.",
            situation="A six-year-old living with her mother in a motel on the outskirts of Disney World. The motel is simultaneously housing, school neighborhood, community, and the border between the fantasy economy and poverty. One bad week away from losing everything.",
            full_landscape="Joyful, imaginative, brave, resourceful — seeing the world as adventure even inside precarity. Her childhood is happening in real-time inside a system that could collapse it at any moment. The magic is real even though the stability isn't.",
            production_challenge="The dome must protect childhood itself — not just housing and benefits, but the conditions under which a child can be a child. The motel-as-housing is a system failure that looks like a lifestyle choice from outside.",
            key_systems=["child welfare", "homelessness prevention", "public education", "Medicaid", "SNAP", "childcare subsidies", "housing assistance"],
            flourishing_dimensions=["childhood", "housing", "imagination", "safety", "education", "play", "stability"],
        ),
    ),
    # SPHERES — parcels from Philadelphia
    ProjectBrief(
        project_id="project-006",
        game_type=GameType.SPHERES,
        title="The Germantown Activation",
        status=ProjectStatus.SOURCED,
        parcel=ParcelBrief(
            address="5501 Germantown Ave",
            neighborhood="Germantown",
            parcel_id="PHL-GRM-5501",
            zoning="CMX-2 (Commercial Mixed Use)",
            lot_size_sqft=8500,
            history="Former commercial building, vacant 7 years. Was a community pharmacy for 40 years before that. The neighborhood remembers it as a gathering place.",
            opportunity="Corner lot with high visibility, existing structure with good bones, adjacent to transit. Could become a community market, maker space, or cultural hub. The neighborhood has the demand — it lacks the activation infrastructure.",
            community_context="Germantown is one of Philadelphia's most historically significant neighborhoods, with deep community organizations but significant vacancy. The population is diverse, multigenerational, and actively organizing for local economic development.",
            constraints=["Environmental assessment needed", "ADA compliance required for existing structure", "Parking variance likely needed"],
        ),
    ),
    ProjectBrief(
        project_id="project-007",
        game_type=GameType.SPHERES,
        title="The Point Breeze Activation",
        status=ProjectStatus.SOURCED,
        parcel=ParcelBrief(
            address="1700 Block S 20th St",
            neighborhood="Point Breeze",
            parcel_id="PHL-PB-1700",
            zoning="RSA-5 (Residential)",
            lot_size_sqft=12000,
            history="Series of 4 connected vacant lots, formerly rowhouses demolished in 2015. The lots have been community-maintained as informal green space — someone planted tomatoes, someone put out chairs.",
            opportunity="The community is already using this space. The activation formalizes and amplifies what's organically happening — community garden, gathering space, potentially a micro-market. The informality is the proof of concept.",
            community_context="Point Breeze is experiencing rapid gentrification alongside persistent poverty. Long-term residents and new arrivals have different relationships to vacant space. Any activation must serve both populations.",
            constraints=["Multiple lot consolidation required", "Residential zoning limits commercial use", "Community land trust structure recommended to prevent displacement"],
        ),
    ),
    ProjectBrief(
        project_id="project-008",
        game_type=GameType.SPHERES,
        title="The Kensington Activation",
        status=ProjectStatus.SOURCED,
        parcel=ParcelBrief(
            address="2800 Kensington Ave",
            neighborhood="Kensington",
            parcel_id="PHL-KEN-2800",
            zoning="IRMX (Industrial Residential Mixed Use)",
            lot_size_sqft=22000,
            history="Former textile factory, partially demolished, foundation and partial walls remain. The neighborhood's industrial heritage is written in the remaining brickwork. Currently a dumping ground but the community remembers what it was.",
            opportunity="The industrial shell provides structure and character. The mixed-use zoning allows creative programming. Could become a maker space, community workshop, performance venue, or hybrid. The ruins are an asset, not a liability.",
            community_context="Kensington faces the opioid crisis alongside a deep tradition of working-class solidarity, immigrant community, and DIY culture. The neighborhood has extraordinary informal mutual aid networks that any activation should amplify, not replace.",
            constraints=["Environmental remediation required", "Structural assessment of remaining walls", "Loading dock access could enable logistics programming"],
        ),
    ),
    ProjectBrief(
        project_id="project-009",
        game_type=GameType.SPHERES,
        title="The North Philadelphia Activation",
        status=ProjectStatus.SOURCED,
        parcel=ParcelBrief(
            address="2200 N Broad St (adjacent lot)",
            neighborhood="North Philadelphia",
            parcel_id="PHL-NBR-2200",
            zoning="CMX-3 (Commercial Mixed Use)",
            lot_size_sqft=15000,
            history="Vacant since 2008. Was a gas station, then briefly a used car lot. Surrounded by institutions — Temple University nearby, community health centers, churches. An institutional neighborhood with a hole in its center.",
            opportunity="Positioned between institutional anchors. The activation could connect what's already there — a public square, a market, a performance space that serves the university AND the long-term residents. The site's emptiness is a communication failure between institutions that are 2 blocks apart.",
            community_context="North Broad is the boundary between Temple University's expansion and historic Black neighborhoods. The activation must bridge, not divide. Long-term residents have deep suspicion of university-driven development.",
            constraints=["Previous gas station requires environmental study", "High traffic requires careful pedestrian design", "Community benefit agreement should precede development"],
        ),
    ),
    ProjectBrief(
        project_id="project-010",
        game_type=GameType.SPHERES,
        title="The Southwest Philadelphia Activation",
        status=ProjectStatus.SOURCED,
        parcel=ParcelBrief(
            address="6100 Woodland Ave",
            neighborhood="Southwest Philadelphia",
            parcel_id="PHL-SW-6100",
            zoning="CMX-2 (Commercial Mixed Use)",
            lot_size_sqft=6000,
            history="Former corner store, vacant 4 years. The awning frame is still there. The neighborhood still walks to this corner out of habit. The lot is small but the intersection is active — bus stop, school route, church on the opposite corner.",
            opportunity="Small-scale activation with outsized impact. The corner is already a gathering point — the activation gives it form. A food stand, a news kiosk, a micro-gallery, a neighborhood information hub. The awning frame is a gift — shade and identity already built.",
            community_context="Southwest Philadelphia has a large immigrant population — Liberian, Vietnamese, Caribbean communities. The corner store was a polyglot space. Any activation should honor that multilingual, multicultural character.",
            constraints=["Small footprint requires efficient design", "Adjacent to bus stop — coordination with SEPTA needed", "Multilingual signage and programming essential"],
        ),
    ),
]
