/**
 * CHARACTER FRAGMENT — Film, TV, and Documentary Sources
 *
 * Characters from film, television, and documentary whose circumstances
 * are documented with enough specificity to build domes.
 *
 * For documentaries: real people documented through film.
 * For fiction: characters whose circumstances are rendered with precision.
 */

export default [

  // ══════════════════════════════════════════════════════════════════════════════
  // DOCUMENTARY — Real People
  // ══════════════════════════════════════════════════════════════════════════════

  {
    name: 'William Gates',
    real_or_fictional: 'real',
    source_work: 'Hoop Dreams',
    source_author_creator: 'Steve James, Frederick Marx, Peter Gilbert',
    source_year: 1994,
    circumstances: ['poverty', 'housing_insecure', 'dropout'],
    location: 'Cabrini-Green, Chicago, IL; Suburban Chicago',
    time_period: '1986-1991',
    systems_touched: ['public schools', 'private schools (St. Joseph)', 'basketball recruitment', 'college athletics', 'public housing'],
    dome_layer_richness: { 1: 4, 2: 5, 3: 7, 4: 5, 5: 8, 6: 7, 7: 8, 8: 9, 9: 7, 10: 7, 11: 6, 12: 7 },
    key_relationships: ['Arthur Agee', 'Emma Gates (mother)', 'Curtis Gates (brother)', 'Coach Pingatore', 'Family'],
    narrative_arc: 'Recruited from Cabrini-Green to a suburban private school for basketball. The documentary follows him for 5 years — the bus commute between worlds, the knee injury that threatens everything, the academic gaps between his neighborhood school and St. Joseph\'s, the weight of being his family\'s lottery ticket.',
    why_this_character_matters: 'William\'s dome maps the recruitment pipeline — how athletics becomes the only visible pathway out of public housing, and how that pathway requires navigating two completely different dome environments (Cabrini-Green and suburban Chicago) simultaneously.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Arthur Agee',
    real_or_fictional: 'real',
    source_work: 'Hoop Dreams',
    source_author_creator: 'Steve James, Frederick Marx, Peter Gilbert',
    source_year: 1994,
    circumstances: ['poverty', 'housing_insecure', 'addiction', 'dropout'],
    location: 'West Garfield Park, Chicago, IL',
    time_period: '1986-1991',
    systems_touched: ['public schools', 'private school (expelled)', 'welfare', 'drug economy', 'community college athletics', 'public housing'],
    dome_layer_richness: { 1: 5, 2: 5, 3: 7, 4: 5, 5: 8, 6: 7, 7: 7, 8: 9, 9: 7, 10: 6, 11: 6, 12: 6 },
    key_relationships: ['William Gates', 'Bo Agee (father)', 'Sheila Agee (mother)', 'Coach Bedford'],
    narrative_arc: 'The mirror to William — also recruited, then cut when the school decided he wasn\'t good enough. Returns to the neighborhood school, watches his father descend into crack addiction, sees basketball as the only remaining door. The documentary\'s most devastating sequence: his father stealing from the family to buy drugs.',
    why_this_character_matters: 'Arthur and William are the same dome experiment with different Layer 8 (Community) variables. Same starting conditions, different family stability, different outcomes. Comparing their domes reveals which community factors are decisive.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Steven Avery',
    real_or_fictional: 'real',
    source_work: 'Making a Murderer',
    source_author_creator: 'Laura Ricciardi, Moira Demos',
    source_year: 2015,
    circumstances: ['wrongly_convicted', 'incarcerated', 'formerly_incarcerated', 'poverty'],
    location: 'Manitowoc County, WI',
    time_period: '1985-2015',
    systems_touched: ['criminal justice', 'DNA exoneration', 'civil lawsuit', 'Manitowoc County Sheriff', 'public defender', 'prison'],
    dome_layer_richness: { 1: 10, 2: 6, 3: 7, 4: 5, 5: 6, 6: 6, 7: 4, 8: 7, 9: 5, 10: 9, 11: 3, 12: 5 },
    key_relationships: ['Brendan Dassey (nephew)', 'Family', 'Dean Strang and Jerry Buting (lawyers)', 'Teresa Halbach'],
    narrative_arc: 'Wrongly convicted, served 18 years, exonerated by DNA, then accused of murder while suing the county for $36 million. The documentary raises the question of whether the second prosecution was retaliation. 10 episodes of legal system documentation — every motion, every hearing, every manipulation.',
    why_this_character_matters: 'Steven\'s dome maps how the legal system responds to being proven wrong. His first dome (wrongful conviction) collapsed. His second dome (freedom + lawsuit) was then demolished by the same system. The dome reveals whether systems can self-correct or only self-protect.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Dark Days Tunnel Dwellers',
    real_or_fictional: 'real',
    source_work: 'Dark Days',
    source_author_creator: 'Marc Singer',
    source_year: 2000,
    circumstances: ['homeless', 'addiction', 'poverty', 'deep_poverty', 'mental_illness'],
    location: 'Freedom Tunnel (Amtrak tunnel under Riverside Park), New York City, NY',
    time_period: '1994-1997',
    systems_touched: ['Amtrak (unwitting landlord)', 'shelters (avoided)', 'scavenging economy', 'Coalition for the Homeless', 'Section 8 (eventual)'],
    dome_layer_richness: { 1: 4, 2: 5, 3: 6, 4: 7, 5: 10, 6: 6, 7: 3, 8: 9, 9: 9, 10: 8, 11: 6, 12: 6 },
    key_relationships: ['Each other (tunnel community)', 'Marc Singer (filmmaker)'],
    narrative_arc: 'Community of homeless people living in an abandoned Amtrak tunnel under Manhattan\'s Upper West Side. They built homes — with electricity tapped from above, furniture scavenged from the street, pets, gardens. Singer (himself homeless, living in the tunnel) documents a functioning community in the most extreme environment.',
    why_this_character_matters: 'The tunnel dwellers built a dome from nothing, underground. Layer 8 (Community) is at maximum — they formed a society. Layer 9 (Environment) is extraordinary — the tunnel itself. Their dome reveals that community can exist where all other layers are absent.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Keire Johnson',
    real_or_fictional: 'real',
    source_work: 'Minding the Gap',
    source_author_creator: 'Bing Liu',
    source_year: 2018,
    circumstances: ['domestic_violence', 'poverty', 'trauma', 'bereavement'],
    location: 'Rockford, IL',
    time_period: '2012-2017',
    systems_touched: ['schools', 'skateparks (informal community)', 'restaurants (employment)', 'domestic violence services'],
    dome_layer_richness: { 1: 4, 2: 3, 3: 5, 4: 6, 5: 5, 6: 6, 7: 5, 8: 8, 9: 6, 10: 7, 11: 8, 12: 7 },
    key_relationships: ['Bing Liu', 'Zack', 'Father (abuser, deceased)', 'Skateboarding community'],
    narrative_arc: 'Young Black man in Rockford processing his father\'s abuse after his father\'s death. Liu documents how skateboarding culture becomes a substitute family, how the physical act of skating is a form of therapy, and how domestic violence echoes through working-class communities across racial lines.',
    why_this_character_matters: 'Keire\'s dome fills Layer 11 (Creativity) with skateboarding — physical expression as meaning-making. His dome reveals how informal community (a skatepark) can fill functions that formal systems (therapy, family) fail to provide.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Halley',
    real_or_fictional: 'fictional',
    source_work: 'The Florida Project',
    source_author_creator: 'Sean Baker',
    source_year: 2017,
    circumstances: ['homeless', 'poverty', 'single_parent', 'housing_insecure', 'addiction'],
    location: 'Kissimmee, FL (motels near Disney World)',
    time_period: '2017',
    systems_touched: ['motel system (hidden homelessness)', 'welfare', 'child welfare (DCF)', 'sex work', 'fast food employment', 'schools'],
    dome_layer_richness: { 1: 5, 2: 6, 3: 8, 4: 5, 5: 10, 6: 7, 7: 4, 8: 7, 9: 7, 10: 6, 11: 4, 12: 4 },
    key_relationships: ['Moonee (daughter)', 'Bobby (motel manager)', 'Ashley (friend)', 'Other motel families'],
    narrative_arc: 'Single mother living in a budget motel outside Disney World — technically homeless but not in a shelter, invisible to homelessness statistics. Baker documents the economics of motel poverty — weekly rates that exceed monthly rent, no kitchen, no lease protections, one paycheck from the street. When she turns to sex work to pay the motel, DCF comes for Moonee.',
    why_this_character_matters: 'Halley\'s dome maps hidden homelessness — the motel economy that doesn\'t count as homeless but isn\'t housing. Her Layer 5 is the liminal space between shelter and home. Her dome reveals a population that no government system sees or serves.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // TELEVISION — Fictional Characters with Deep Circumstance Documentation
  // ══════════════════════════════════════════════════════════════════════════════

  {
    name: 'Omar Little',
    real_or_fictional: 'fictional',
    source_work: 'The Wire',
    source_author_creator: 'David Simon, Ed Burns',
    source_year: 2002,
    circumstances: ['poverty', 'homeless', 'formerly_incarcerated'],
    location: 'West Baltimore, MD',
    time_period: '2002-2008',
    systems_touched: ['drug economy (robbing dealers)', 'courts', 'prison', 'hospitals', 'community (street code)'],
    dome_layer_richness: { 1: 8, 2: 4, 3: 6, 4: 5, 5: 6, 6: 7, 7: 3, 8: 9, 9: 7, 10: 9, 11: 5, 12: 6 },
    key_relationships: ['Brandon', 'Donnie', 'Bunk Moreland', 'Avon Barksdale', 'Marlo Stanfield'],
    narrative_arc: 'Gay stick-up artist who robs drug dealers with a code — he never targets civilians. Simon uses Omar to document the parallel legal system of the street — its own courts (respect), its own penalties (violence), its own honor code. Omar navigates the street system more skillfully than the police navigate the legal one.',
    why_this_character_matters: 'Omar\'s dome maps the shadow legal system. Layer 1 (Legal) has two versions in his dome — the formal law that hunts him and the street law he enforces. Building his dome reveals how informal justice systems emerge when formal ones are absent or hostile.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Bubbles (Reginald Cousins)',
    real_or_fictional: 'fictional',
    source_work: 'The Wire',
    source_author_creator: 'David Simon, Ed Burns',
    source_year: 2002,
    circumstances: ['addiction', 'homeless', 'poverty', 'deep_poverty', 'trauma', 'bereavement'],
    location: 'West Baltimore, MD',
    time_period: '2002-2008',
    systems_touched: ['drug economy', 'police (informant)', 'homeless services', 'rehab (multiple)', 'hospitals', 'NA meetings', 'newspaper (selling)'],
    dome_layer_richness: { 1: 6, 2: 6, 3: 6, 4: 9, 5: 8, 6: 7, 7: 3, 8: 8, 9: 7, 10: 8, 11: 4, 12: 8 },
    key_relationships: ['Johnny (partner)', 'Kima Greggs (detective)', 'Walon (sponsor)', 'Sherrod (protégé)', 'Sister'],
    narrative_arc: 'Heroin addict whose arc across all five seasons is the most complete addiction-recovery-relapse-recovery narrative in television. Simon documents every institutional encounter — the rehab that doesn\'t work, the homelessness between relapses, the police who use him as an informant, and ultimately the NA meeting and the sister\'s house that save him.',
    why_this_character_matters: 'Bubbles\' dome across 5 seasons is the most granular addiction dome in fiction. Each season is a different dome configuration — same person, different layer states. His dome proves that recovery requires multiple layers to change simultaneously, not just Layer 4 (Health).',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'D\'Angelo Barksdale',
    real_or_fictional: 'fictional',
    source_work: 'The Wire',
    source_author_creator: 'David Simon, Ed Burns',
    source_year: 2002,
    circumstances: ['incarcerated', 'poverty', 'trauma'],
    location: 'West Baltimore, MD; Jessup Correctional Institution',
    time_period: '2002-2003',
    systems_touched: ['drug organization', 'criminal justice', 'prison', 'public housing (the pit, the towers)'],
    dome_layer_richness: { 1: 9, 2: 5, 3: 7, 4: 6, 5: 7, 6: 7, 7: 5, 8: 8, 9: 7, 10: 8, 11: 5, 12: 6 },
    key_relationships: ['Avon Barksdale (uncle)', 'Brianna (mother)', 'Donette (partner)', 'Wallace', 'Stringer Bell'],
    narrative_arc: 'Nephew of a drug kingpin who doesn\'t want to be in the game. Simon documents his attempt to walk away — and the impossibility of it. D\'Angelo reads The Great Gatsby in prison and sees himself in it. His murder (made to look like suicide) is ordered by his own uncle to protect the organization.',
    why_this_character_matters: 'D\'Angelo\'s dome maps the trap — Layer 8 (Community) and Layer 1 (Legal) conspire to prevent exit. His dome reveals that some communities are prisons, and some prisons offer more freedom than the community.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Walter White',
    real_or_fictional: 'fictional',
    source_work: 'Breaking Bad',
    source_author_creator: 'Vince Gilligan',
    source_year: 2008,
    circumstances: ['terminal_illness', 'debt', 'working_poor', 'uninsured'],
    location: 'Albuquerque, NM',
    time_period: '2008-2010',
    systems_touched: ['public schools (teacher)', 'hospitals', 'insurance (insufficient)', 'car wash (second job)', 'DEA', 'criminal justice', 'drug economy'],
    dome_layer_richness: { 1: 8, 2: 5, 3: 10, 4: 10, 5: 6, 6: 8, 7: 8, 8: 7, 9: 5, 10: 8, 11: 5, 12: 7 },
    key_relationships: ['Skyler (wife)', 'Walter Jr. (son)', 'Jesse Pinkman', 'Hank Schrader (DEA brother-in-law)', 'Gustavo Fring'],
    narrative_arc: 'Chemistry teacher diagnosed with cancer who can\'t afford treatment on his salary. Gilligan documents the fiscal architecture that drives the plot — the exact gap between a teacher\'s insurance and cancer treatment costs, the second job at a car wash, the student loan debt, the new baby. Walter doesn\'t cook meth because he\'s evil; he cooks meth because the healthcare system is broken.',
    why_this_character_matters: 'Walter White is the most famous fictional argument that the American healthcare system creates crime. His dome\'s Layer 3 (Fiscal) and Layer 4 (Health) gap IS the entire plot. Building his dome with real ACA-era insurance reveals whether his story is still possible.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // FILM — International
  // ══════════════════════════════════════════════════════════════════════════════

  {
    name: 'Ki-taek Kim (The Kim Family)',
    real_or_fictional: 'fictional',
    source_work: 'Parasite',
    source_author_creator: 'Bong Joon-ho',
    source_year: 2019,
    circumstances: ['poverty', 'housing_insecure', 'unemployed', 'environmental_exposure'],
    location: 'Seoul, South Korea (semi-basement banjiha)',
    time_period: '2019',
    systems_touched: ['gig economy (pizza box folding)', 'fumigation (exposure)', 'flooding (infrastructure failure)', 'employment agencies', 'schools'],
    dome_layer_richness: { 1: 4, 2: 4, 3: 8, 4: 5, 5: 10, 6: 8, 7: 5, 8: 7, 9: 9, 10: 7, 11: 4, 12: 5 },
    key_relationships: ['Chung-sook (wife)', 'Ki-woo (son)', 'Ki-jung (daughter)', 'Park family (employers)'],
    narrative_arc: 'Family of four living in a semi-basement apartment that floods when it rains. Bong documents the vertical architecture of class — the Kims below ground, the Parks above, and the secret man hidden in the sub-basement. Each family occupies a different altitude in the same city, and water flows downhill.',
    why_this_character_matters: 'The Kim family dome maps class as architecture. Layer 5 (Housing) is literally underground. Layer 9 (Environment) shows how infrastructure failure (flooding) targets the lowest residents. Their dome vs. the Park family dome is the same city measured at different altitudes.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Cleo',
    real_or_fictional: 'fictional',
    source_work: 'Roma',
    source_author_creator: 'Alfonso Cuarón',
    source_year: 2018,
    circumstances: ['poverty', 'working_poor', 'immigrant', 'domestic_violence', 'bereavement'],
    location: 'Roma neighborhood, Mexico City, Mexico',
    time_period: '1970-1971',
    systems_touched: ['domestic service', 'hospitals', 'political protests', 'martial arts dojos', 'community'],
    dome_layer_richness: { 1: 4, 2: 3, 3: 6, 4: 7, 5: 7, 6: 8, 7: 4, 8: 8, 9: 7, 10: 7, 11: 5, 12: 7 },
    key_relationships: ['Sofía (employer)', 'Children she cares for', 'Fermín (boyfriend)', 'Adela (fellow domestic worker)'],
    narrative_arc: 'Indigenous domestic worker in a middle-class Mexico City household. Cuarón documents her pregnancy (by a man who abandons her), the earthquake, the Corpus Christi massacre, and the ocean scene where she saves the children despite not knowing how to swim. Her dome is invisible to the family she serves — she lives inside their dome but has her own, smaller, more fragile one.',
    why_this_character_matters: 'Cleo occupies a dome inside a dome — she lives in her employer\'s house but has a separate, thinner dome. Her dome reveals the domestic worker paradox: physical proximity to wealth with zero access to its protections.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Daniel Blake',
    real_or_fictional: 'fictional',
    source_work: 'I, Daniel Blake',
    source_author_creator: 'Ken Loach',
    source_year: 2016,
    circumstances: ['disability', 'poverty', 'elderly', 'unemployed', 'housing_insecure'],
    location: 'Newcastle, England',
    time_period: '2016',
    systems_touched: ['NHS', 'DWP (benefits)', 'Jobcentre Plus', 'Universal Credit', 'food bank', 'housing association', 'appeals tribunal'],
    dome_layer_richness: { 1: 6, 2: 10, 3: 8, 4: 8, 5: 6, 6: 7, 7: 4, 8: 7, 9: 5, 10: 8, 11: 4, 12: 7 },
    key_relationships: ['Katie Morgan', 'China (friend)', 'DWP staff', 'Food bank volunteers'],
    narrative_arc: 'Carpenter who had a heart attack and can\'t work but is deemed "fit for work" by a computer assessment. Loach documents every step of the UK benefits system — the online-only application he can\'t navigate, the Jobcentre sanctions, the food bank, the appeal tribunal. He dies of a heart attack in the waiting room of the appeals office.',
    why_this_character_matters: 'Daniel Blake is the most detailed fictional map of benefits system navigation ever filmed. Layer 2 (Systems) is documented with such precision that the film was used as evidence in UK parliamentary hearings on welfare reform. His dome maps the bureaucratic kill zone.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Ladj Ly Neighborhood Characters (Les Misérables)',
    real_or_fictional: 'fictional',
    source_work: 'Les Misérables (2019 film)',
    source_author_creator: 'Ladj Ly',
    source_year: 2019,
    circumstances: ['poverty', 'housing_insecure', 'immigrant', 'surveillance', 'environmental_exposure'],
    location: 'Montfermeil (banlieue), Paris, France',
    time_period: '2019',
    systems_touched: ['police (BAC anti-crime brigade)', 'public housing (HLM)', 'mosques', 'community leaders', 'drone surveillance', 'schools'],
    dome_layer_richness: { 1: 8, 2: 5, 3: 5, 4: 4, 5: 8, 6: 5, 7: 5, 8: 9, 9: 7, 10: 7, 11: 4, 12: 4 },
    key_relationships: ['Stéphane (new cop)', 'Chris and Gwada (experienced cops)', 'The Mayor (community boss)', 'Issa (the boy)'],
    narrative_arc: 'One day in a Paris banlieue where police shoot a boy with a rubber bullet and a drone captures it on video. Ly documents the parallel governance structures — police, mosque leaders, community bosses, and drug dealers all compete for authority in a housing project the state has abandoned.',
    why_this_character_matters: 'This dome maps the French banlieue as a parallel system — Layer 1 (Legal) is the police, but Layer 8 (Community) has its own competing authority. The drone footage becomes the layer that forces all other layers to reckon with what happened.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },
]
