/**
 * CHARACTER FRAGMENT — Literature Sources (Fictional Characters)
 *
 * Characters from novels, novellas, and short fiction whose circumstances
 * are rendered with enough specificity to build domes. The fiction is
 * the source material. The dome built from it uses real law, real systems,
 * real costs applied to the character's documented circumstances.
 */

export default [

  // ══════════════════════════════════════════════════════════════════════════════
  // AMERICAN LITERATURE
  // ══════════════════════════════════════════════════════════════════════════════

  {
    name: 'Bigger Thomas',
    real_or_fictional: 'fictional',
    source_work: 'Native Son',
    source_author_creator: 'Richard Wright',
    source_year: 1940,
    circumstances: ['poverty', 'incarcerated', 'housing_insecure', 'unemployed', 'trauma'],
    location: 'South Side Chicago, IL',
    time_period: '1930s',
    systems_touched: ['criminal justice', 'courts', 'public defender', 'welfare', 'public housing', 'employment agencies'],
    dome_layer_richness: { 1: 10, 2: 5, 3: 7, 4: 6, 5: 9, 6: 8, 7: 4, 8: 9, 9: 8, 10: 9, 11: 4, 12: 6 },
    key_relationships: ['Vera and Buddy (siblings)', 'Mrs. Thomas (mother)', 'Mary Dalton', 'Bessie', 'Boris Max (lawyer)'],
    narrative_arc: 'Young Black man confined to the Black Belt of 1930s Chicago by restrictive covenants. Wright documents the physical architecture of segregation — the rat-infested kitchenette apartment, the invisible boundaries of the ghetto, the white neighborhoods he can only enter as a servant. When he accidentally kills, the legal system treats him as the monster it always assumed he was.',
    why_this_character_matters: 'Bigger\'s dome is the foundational text of environmental determinism. Wright argues that every system — housing, legal, economic, community — conspired to create Bigger. Building his dome with real 1930s Chicago data proves or disproves Wright\'s thesis.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Jurgis Rudkus',
    real_or_fictional: 'fictional',
    source_work: 'The Jungle',
    source_author_creator: 'Upton Sinclair',
    source_year: 1906,
    circumstances: ['immigrant', 'poverty', 'working_poor', 'housing_insecure', 'environmental_exposure', 'incarcerated', 'child_labor', 'bereavement'],
    location: 'Packingtown (Back of the Yards), Chicago, IL',
    time_period: '1900s',
    systems_touched: ['meatpacking industry', 'immigration', 'courts', 'jails', 'unions', 'housing (contract buying)', 'political machines', 'hospitals'],
    dome_layer_richness: { 1: 7, 2: 5, 3: 8, 4: 7, 5: 8, 6: 10, 7: 4, 8: 7, 9: 10, 10: 7, 11: 3, 12: 5 },
    key_relationships: ['Ona (wife)', 'Elzbieta (mother-in-law)', 'Children', 'Union organizers', 'Political bosses'],
    narrative_arc: 'Lithuanian immigrant whose entire family is destroyed by the meatpacking industry. Sinclair documents every system failure: the scam home purchase, the injury with no workers comp, the wife\'s sexual assault by a foreman, the child\'s drowning in an unpaved street, the jail for punching the foreman. Layer by layer, every system extracts from him until nothing remains.',
    why_this_character_matters: 'Jurgis is the most complete fictional dome in American literature. Sinclair fills every layer with documented industrial-era conditions. Building his dome with 1906 vs. 2024 systems reveals exactly which protections were added and which gaps remain.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Tom Joad',
    real_or_fictional: 'fictional',
    source_work: 'The Grapes of Wrath',
    source_author_creator: 'John Steinbeck',
    source_year: 1939,
    circumstances: ['formerly_incarcerated', 'displaced', 'poverty', 'homeless', 'unemployed', 'climate_displaced'],
    location: 'Oklahoma → California (Route 66)',
    time_period: '1930s (Dust Bowl)',
    systems_touched: ['criminal justice', 'parole', 'farm labor', 'Hoovervilles', 'migrant camps (government)', 'police', 'growers associations'],
    dome_layer_richness: { 1: 8, 2: 5, 3: 7, 4: 5, 5: 8, 6: 9, 7: 3, 8: 9, 9: 9, 10: 8, 11: 4, 12: 7 },
    key_relationships: ['Ma Joad', 'Pa Joad', 'Jim Casy (preacher)', 'Rose of Sharon', 'Entire Joad family'],
    narrative_arc: 'Returns from prison to find his family evicted by the Dust Bowl and bank foreclosure. Joins the migration to California, where every promise of work is a trap. Steinbeck documents the economics of exploitation — how surplus labor drives wages below survival, how police serve growers, how government camps are the only humane response.',
    why_this_character_matters: 'Tom Joad\'s dome maps climate displacement in the American context. Layer 9 (Environment — the Dust Bowl) destroys Layer 5 (Housing) and Layer 6 (Economic), creating mass migration that overwhelms every system in the destination. His story is climate migration before we had the term.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Celie',
    real_or_fictional: 'fictional',
    source_work: 'The Color Purple',
    source_author_creator: 'Alice Walker',
    source_year: 1982,
    circumstances: ['domestic_violence', 'poverty', 'illiterate', 'child_marriage', 'trauma', 'isolation'],
    location: 'Rural Georgia',
    time_period: '1910s-1940s',
    systems_touched: ['sharecropping', 'churches', 'domestic service', 'informal economy (pants-making business)'],
    dome_layer_richness: { 1: 6, 2: 3, 3: 6, 4: 6, 5: 6, 6: 7, 7: 5, 8: 8, 9: 5, 10: 10, 11: 9, 12: 10 },
    key_relationships: ['Mister (Albert)', 'Shug Avery', 'Nettie (sister)', 'Sofia', 'Harpo'],
    narrative_arc: 'Given away as a child bride, brutalized by her husband, separated from her sister. Celie\'s transformation comes through love (Shug), creativity (pants-making), and literacy (letters). Walker documents every dimension of Southern Black women\'s oppression and then maps every dimension of liberation — all without any formal system intervening.',
    why_this_character_matters: 'Celie\'s dome is defined by the absence of systems and the presence of community. Layer 2 (Systems) is empty — no government helped her. Layer 8 (Community), Layer 11 (Creativity), and Layer 12 (Flourishing) are what saved her. Her dome proves that human layers can compensate for empty institutional layers.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Sethe',
    real_or_fictional: 'fictional',
    source_work: 'Beloved',
    source_author_creator: 'Toni Morrison',
    source_year: 1987,
    circumstances: ['enslaved', 'refugee', 'domestic_violence', 'trauma', 'grief', 'isolation', 'mental_illness'],
    location: '124 Bluestone Road, Cincinnati, OH (Sweet Home, KY)',
    time_period: '1850s-1870s',
    systems_touched: ['slavery', 'Fugitive Slave Act', 'Underground Railroad', 'community (both supporting and shunning)'],
    dome_layer_richness: { 1: 9, 2: 3, 3: 4, 4: 8, 5: 8, 6: 5, 7: 3, 8: 9, 9: 5, 10: 10, 11: 7, 12: 9 },
    key_relationships: ['Beloved (daughter/ghost)', 'Denver (daughter)', 'Paul D', 'Baby Suggs', 'Schoolteacher (enslaver)'],
    narrative_arc: 'Escaped from slavery and killed her own daughter rather than let her be returned to bondage. Morrison documents the interior architecture of slavery\'s aftermath — not just the physical scars on Sethe\'s back (shaped like a tree) but the way memory itself becomes a haunting. The house at 124 is both shelter and prison.',
    why_this_character_matters: 'Sethe\'s dome maps trauma as a layer that sits on top of all others. Her Layer 10 (Autonomy) action — killing her child to free it — is the most extreme autonomy claim in this catalog. Building her dome reveals whether any system could have offered an alternative.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Esperanza Cordero',
    real_or_fictional: 'fictional',
    source_work: 'The House on Mango Street',
    source_author_creator: 'Sandra Cisneros',
    source_year: 1984,
    circumstances: ['poverty', 'housing_insecure', 'immigrant'],
    location: 'Mango Street, Chicago, IL (Humboldt Park/Pilsen)',
    time_period: '1960s-1970s',
    systems_touched: ['public schools', 'public housing', 'churches', 'neighborhood'],
    dome_layer_richness: { 1: 3, 2: 3, 3: 5, 4: 3, 5: 9, 6: 5, 7: 6, 8: 9, 9: 7, 10: 7, 11: 9, 12: 8 },
    key_relationships: ['Rachel and Lucy (friends)', 'Sally', 'Parents', 'Mango Street neighbors'],
    narrative_arc: 'Young Latina girl who wants a house of her own — not the crumbling house on Mango Street. Cisneros renders the neighborhood with poetic precision: every house, every family, every yard. Esperanza maps her world through architecture — houses as destiny, houses as identity, houses as escape.',
    why_this_character_matters: 'Esperanza fills Layer 5 (Housing) with the experiential dimension no data can capture — what it feels like to be ashamed of where you live. Her dome links housing shame to identity formation to creative ambition.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Offred (June)',
    real_or_fictional: 'fictional',
    source_work: 'The Handmaid\'s Tale',
    source_author_creator: 'Margaret Atwood',
    source_year: 1985,
    circumstances: ['detained', 'surveillance', 'forced_labor', 'trafficking', 'trauma'],
    location: 'Republic of Gilead (formerly Cambridge, MA)',
    time_period: 'Near future',
    systems_touched: ['theocratic government', 'Aunts (training)', 'Commanders (assignment)', 'Eyes (secret police)', 'Underground resistance'],
    dome_layer_richness: { 1: 10, 2: 8, 3: 4, 4: 7, 5: 7, 6: 4, 7: 5, 8: 6, 9: 5, 10: 10, 11: 6, 12: 7 },
    key_relationships: ['Commander Fred', 'Serena Joy', 'Nick', 'Moira', 'Ofglen', 'Luke (husband, before)'],
    narrative_arc: 'Woman enslaved as a reproductive vessel in a theocratic state. Atwood documents the architecture of total control — the uniform, the restricted walking routes, the forbidden reading, the mandated rape ceremony, and the small resistances (butter on skin, whispered words).',
    why_this_character_matters: 'Offred\'s dome maps a system designed to destroy Layers 10-12 (Autonomy, Creativity, Flourishing) while maintaining Layers 1-5. Her dome reveals that a person can be housed, fed, and medically maintained while having zero autonomy. The dome\'s COSM score would be zero despite filled lower layers.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Huckleberry Finn',
    real_or_fictional: 'fictional',
    source_work: 'Adventures of Huckleberry Finn',
    source_author_creator: 'Mark Twain',
    source_year: 1884,
    circumstances: ['orphan', 'homeless', 'domestic_violence', 'poverty', 'child_labor'],
    location: 'Mississippi River (Missouri, Illinois, Arkansas)',
    time_period: '1840s',
    systems_touched: ['widow\'s guardianship', 'schools (ran away)', 'courts (custody)', 'slavery system', 'river economy'],
    dome_layer_richness: { 1: 7, 2: 3, 3: 5, 4: 4, 5: 7, 6: 5, 7: 5, 8: 8, 9: 7, 10: 9, 11: 5, 12: 7 },
    key_relationships: ['Jim', 'Tom Sawyer', 'Pap Finn', 'The Widow Douglas', 'The King and the Duke'],
    narrative_arc: 'Abused boy who fakes his own death to escape his father and rides a raft down the Mississippi with an escaped slave. Twain documents every social system they encounter — the feuding families, the con artists, the slave catchers, the "respectable" people who enable slavery. Huck\'s moral journey: deciding that saving Jim from slavery is worth going to hell.',
    why_this_character_matters: 'Huck\'s dome maps a child navigating antebellum America with no adult protection. Layer 10 (Autonomy) is maximized — he is totally free on the raft — while Layer 1 (Legal) is hostile. His dome reveals the tension between freedom and protection for children.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Pecola Breedlove',
    real_or_fictional: 'fictional',
    source_work: 'The Bluest Eye',
    source_author_creator: 'Toni Morrison',
    source_year: 1970,
    circumstances: ['poverty', 'domestic_violence', 'trauma', 'mental_illness', 'foster_care'],
    location: 'Lorain, OH',
    time_period: '1941',
    systems_touched: ['schools', 'community', 'churches', 'informal foster placement'],
    dome_layer_richness: { 1: 4, 2: 3, 3: 5, 4: 7, 5: 6, 6: 5, 7: 6, 8: 8, 9: 5, 10: 9, 11: 4, 12: 6 },
    key_relationships: ['Cholly Breedlove (father/rapist)', 'Pauline Breedlove (mother)', 'Claudia and Frieda MacTeer', 'Soaphead Church'],
    narrative_arc: 'Black girl who prays for blue eyes because she has internalized white beauty standards as a survival strategy. Morrison documents how racism enters through aesthetics — through Dick-and-Jane readers, through Shirley Temple cups, through every cultural message that says Black is ugly. Raped by her father, she retreats into madness.',
    why_this_character_matters: 'Pecola\'s dome maps how cultural violence (Layer 11 — Creativity/Identity) can destroy a person more thoroughly than any institutional system. Her dome would show thin institutional layers but devastated human layers.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // WORLD LITERATURE
  // ══════════════════════════════════════════════════════════════════════════════

  {
    name: 'Jean Valjean',
    real_or_fictional: 'fictional',
    source_work: 'Les Misérables',
    source_author_creator: 'Victor Hugo',
    source_year: 1862,
    circumstances: ['incarcerated', 'formerly_incarcerated', 'poverty', 'deep_poverty', 'homeless', 'orphan'],
    location: 'Digne, Montreuil-sur-Mer, Paris, France',
    time_period: '1815-1832',
    systems_touched: ['prison (bagne)', 'parole (yellow passport)', 'factories', 'municipal government', 'courts', 'sewers', 'convents', 'barricades'],
    dome_layer_richness: { 1: 10, 2: 6, 3: 8, 4: 5, 5: 8, 6: 8, 7: 4, 8: 8, 9: 6, 10: 9, 11: 4, 12: 9 },
    key_relationships: ['Cosette', 'Fantine', 'Javert', 'Bishop Myriel', 'Marius', 'Thénardiers'],
    narrative_arc: '19 years in prison for stealing bread. Hugo documents every system the ex-convict touches — the yellow passport that marks him, the inns that refuse him, the factory he builds, the mayor he becomes, the identity he hides, the daughter he saves. His dome is the most comprehensive fictional tracking of how criminal records shape an entire life.',
    why_this_character_matters: 'Jean Valjean is the original "formerly incarcerated person navigating systems" story. Hugo wrote it specifically to indict the systems that punish poverty. Building Valjean\'s dome with modern French AND American systems reveals what has and hasn\'t changed in 160 years.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Gregor Samsa',
    real_or_fictional: 'fictional',
    source_work: 'The Metamorphosis',
    source_author_creator: 'Franz Kafka',
    source_year: 1915,
    circumstances: ['disability', 'isolation', 'working_poor', 'caregiver'],
    location: 'Prague (unspecified city)',
    time_period: '1910s',
    systems_touched: ['traveling salesman industry', 'family as economic unit', 'landlords', 'domestic service'],
    dome_layer_richness: { 1: 3, 2: 2, 3: 8, 4: 9, 5: 8, 6: 9, 7: 3, 8: 8, 9: 5, 10: 9, 11: 5, 12: 7 },
    key_relationships: ['Grete (sister)', 'Parents', 'Chief clerk', 'Charwoman'],
    narrative_arc: 'Wakes up as a giant insect. Kafka documents the economic and social consequences with bureaucratic precision — the missed work, the family\'s financial ruin, the shrinking room, the family\'s transformation from dependence to revulsion to abandonment. The metamorphosis is disability rendered as genre.',
    why_this_character_matters: 'Gregor is disability as architecture. His dome maps what happens when a provider becomes a dependent — every layer inverts. Layer 6 (Economic) collapses, Layer 5 (Housing) contracts to a single room, Layer 8 (Community) shrinks to one sister and then to nobody.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Raskolnikov',
    real_or_fictional: 'fictional',
    source_work: 'Crime and Punishment',
    source_author_creator: 'Fyodor Dostoevsky',
    source_year: 1866,
    circumstances: ['poverty', 'deep_poverty', 'housing_insecure', 'mental_illness', 'dropout', 'incarcerated'],
    location: 'St. Petersburg, Russia; Siberia',
    time_period: '1860s',
    systems_touched: ['university (dropped out)', 'pawnbroker economy', 'police', 'courts', 'penal labor (Siberia)'],
    dome_layer_richness: { 1: 8, 2: 3, 3: 7, 4: 8, 5: 8, 6: 6, 7: 6, 8: 6, 9: 6, 10: 8, 11: 4, 12: 8 },
    key_relationships: ['Sonya Marmeladov', 'Razumikhin', 'Porfiry Petrovich (detective)', 'Dunya (sister)', 'Mother'],
    narrative_arc: 'Starving ex-student in a coffin-sized garret who murders a pawnbroker. Dostoevsky documents his poverty with sensory detail — the stench of the stairwell, the heat of a St. Petersburg summer, the delirium of hunger. His confession isn\'t guilt but exhaustion — every system he touches demands performance he cannot sustain.',
    why_this_character_matters: 'Raskolnikov\'s dome maps the interior architecture of poverty-driven crime. His Layer 5 (Housing — the coffin room) and Layer 4 (Health — the fevers) are precisely documented. His dome tests whether circumstance explanations hold up when measured against real systems.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Oliver Twist',
    real_or_fictional: 'fictional',
    source_work: 'Oliver Twist',
    source_author_creator: 'Charles Dickens',
    source_year: 1838,
    circumstances: ['orphan', 'poverty', 'deep_poverty', 'child_labor', 'institutionalized', 'homeless'],
    location: 'London, England (workhouse, Fagin\'s den, Brownlow house)',
    time_period: '1830s',
    systems_touched: ['workhouse', 'parish system', 'apprenticeship', 'criminal underworld', 'courts', 'magistrates'],
    dome_layer_richness: { 1: 7, 2: 8, 3: 6, 4: 6, 5: 8, 6: 7, 7: 4, 8: 8, 9: 7, 10: 8, 11: 3, 12: 5 },
    key_relationships: ['Fagin', 'Bill Sikes', 'Nancy', 'The Artful Dodger', 'Mr. Brownlow', 'Monks'],
    narrative_arc: 'Orphan born in a workhouse, sold as an apprentice, runs away to London, recruited by a criminal gang, rescued by a gentleman. Dickens documents the Victorian child welfare system as a pipeline from workhouse to crime — every "rescue" just moves Oliver to a different form of exploitation.',
    why_this_character_matters: 'Oliver is the original child systems-navigation story. Dickens wrote it to indict the New Poor Law. Building Oliver\'s dome with both Victorian and modern systems reveals whether the workhouse-to-crime pipeline still exists (it does — it\'s now the foster-care-to-prison pipeline).',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Tess Durbeyfield',
    real_or_fictional: 'fictional',
    source_work: 'Tess of the d\'Urbervilles',
    source_author_creator: 'Thomas Hardy',
    source_year: 1891,
    circumstances: ['poverty', 'domestic_violence', 'working_poor', 'housing_insecure', 'incarcerated', 'bereavement'],
    location: 'Wessex (Dorset), England',
    time_period: '1880s-1890s',
    systems_touched: ['farm labor', 'dairy work', 'clergy', 'courts', 'prison', 'estate system'],
    dome_layer_richness: { 1: 8, 2: 3, 3: 7, 4: 5, 5: 7, 6: 8, 7: 4, 8: 7, 9: 7, 10: 9, 11: 4, 12: 7 },
    key_relationships: ['Alec d\'Urberville', 'Angel Clare', 'Family (parents, siblings)'],
    narrative_arc: 'Raped by a wealthy man, abandoned by the husband who can\'t forgive her, driven to murder and execution. Hardy documents every economic pressure — the family\'s poverty that forces her to "claim kin" with Alec, the dairy work that connects her to Angel, the migrant farm labor that breaks her body. Every system pushes her toward destruction.',
    why_this_character_matters: 'Tess\'s dome maps how gender, class, and law conspire. Layer 1 (Legal) defines her as both victim and criminal. Layer 6 (Economic) drives every choice. Building her dome with modern systems reveals which protections now exist that would have saved her.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // MODERN / CONTEMPORARY FICTION
  // ══════════════════════════════════════════════════════════════════════════════

  {
    name: 'Precious Jones',
    real_or_fictional: 'fictional',
    source_work: 'Push',
    source_author_creator: 'Sapphire',
    source_year: 1996,
    circumstances: ['poverty', 'domestic_violence', 'illiterate', 'trauma', 'child_marriage', 'foster_care', 'mental_illness'],
    location: 'Harlem, New York City, NY',
    time_period: '1987-1989',
    systems_touched: ['public schools', 'alternative education (Each One Teach One)', 'welfare', 'child welfare', 'halfway house', 'Medicaid', 'HIV services'],
    dome_layer_richness: { 1: 5, 2: 7, 3: 6, 4: 8, 5: 7, 6: 5, 7: 9, 8: 7, 9: 5, 10: 8, 11: 8, 12: 7 },
    key_relationships: ['Mary (mother)', 'Carl (father/abuser)', 'Ms. Rain (teacher)', 'Abdul and Little Mongo (children)', 'Classmates at Each One Teach One'],
    narrative_arc: 'Illiterate, obese, HIV-positive teenager pregnant by her own father for the second time. Sapphire documents her journey through an alternative literacy program that changes everything. Learning to read and write is the single intervention that unlocks every other layer. Her journal entries — growing from single words to full paragraphs — are the dome building itself in real time.',
    why_this_character_matters: 'Precious proves that Layer 7 (Education) can be the keystone that unlocks all other layers. Her dome before and after literacy are completely different structures. The dome delta from a single intervention (one teacher, one classroom) is the most dramatic in this catalog.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Chiron Harris',
    real_or_fictional: 'fictional',
    source_work: 'In Moonlight Black Boys Look Blue (short story) / Moonlight (film)',
    source_author_creator: 'Tarell Alvin McCraney / Barry Jenkins',
    source_year: 2016,
    circumstances: ['poverty', 'addiction', 'homeless', 'incarcerated', 'isolation', 'trauma'],
    location: 'Liberty City, Miami, FL',
    time_period: '1980s-2000s',
    systems_touched: ['public schools', 'drug economy', 'foster care (informal)', 'prison', 'restaurants (employment)'],
    dome_layer_richness: { 1: 6, 2: 4, 3: 5, 4: 7, 5: 7, 6: 6, 7: 5, 8: 8, 9: 6, 10: 9, 11: 7, 12: 8 },
    key_relationships: ['Juan (drug dealer/father figure)', 'Teresa', 'Paula (mother)', 'Kevin'],
    narrative_arc: 'Three chapters of one life: Little (bullied child), Chiron (teenager discovering sexuality), Black (hardened adult). McCraney/Jenkins document how a queer Black boy in the crack era navigates masculinity, violence, addiction (mother\'s), and love (his own). Each chapter shows the same dome layers filling and emptying as context changes.',
    why_this_character_matters: 'Chiron\'s dome is told in three snapshots — childhood, adolescence, adulthood. The same person, the same circumstances, but different dome configurations at each stage. His dome reveals how layers shift weight over a lifetime.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Turtle Alveston',
    real_or_fictional: 'fictional',
    source_work: 'My Year of Rest and Relaxation',
    source_author_creator: 'Ottessa Moshfegh',
    source_year: 2018,
    circumstances: ['grief', 'mental_illness', 'addiction', 'wealth', 'isolation'],
    location: 'Upper East Side, Manhattan, NY',
    time_period: '2000-2001',
    systems_touched: ['psychiatry', 'pharmacy', 'art world', 'trust funds', 'Columbia University'],
    dome_layer_richness: { 1: 2, 2: 3, 3: 8, 4: 8, 5: 3, 6: 3, 7: 5, 8: 5, 9: 3, 10: 7, 11: 6, 12: 7 },
    key_relationships: ['Dr. Tuttle (psychiatrist)', 'Reva (friend)', 'Ping Xi (artist)'],
    narrative_arc: 'Wealthy, beautiful, bereaved woman who decides to sleep for a year using a cocktail of prescription drugs. Moshfegh documents the pharmacy of privilege — a compliant psychiatrist, unlimited prescriptions, a rent-free apartment. Her dome is filled with resources and empty of meaning.',
    why_this_character_matters: 'This is a wealthy dome — Layer 3 (Fiscal) is maximized, Layer 5 (Housing) is secure, but Layers 10-12 are in crisis. Her dome proves that filling lower layers doesn\'t guarantee flourishing. The COSM score for a rich, devastated person reveals the system\'s blind spots.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Ifemelu',
    real_or_fictional: 'fictional',
    source_work: 'Americanah',
    source_author_creator: 'Chimamanda Ngozi Adichie',
    source_year: 2013,
    circumstances: ['immigrant', 'poverty', 'working_poor', 'housing_insecure', 'undocumented'],
    location: 'Lagos, Nigeria → Philadelphia, PA; Princeton, NJ; Baltimore, MD',
    time_period: '1990s-2010s',
    systems_touched: ['universities', 'immigration (visa), babysitting economy', 'hair salons', 'blogging', 'Trenton DMV'],
    dome_layer_richness: { 1: 7, 2: 6, 3: 7, 4: 4, 5: 6, 6: 7, 7: 8, 8: 7, 9: 4, 10: 7, 11: 8, 12: 7 },
    key_relationships: ['Obinze', 'Aunty Uju', 'Dike (cousin)', 'Curt', 'Blaine'],
    narrative_arc: 'Nigerian woman navigating American immigration, race, and class. Adichie documents the practical mechanics of immigrant survival — expired visas, borrowed Social Security numbers, the hair salon economy, the discovery that she is "Black" in America in a way she never was in Nigeria.',
    why_this_character_matters: 'Ifemelu\'s dome maps how race is a system, not just an identity. Her Layer 1 (Legal — immigration status) and Layer 8 (Community — racial classification) are completely reconfigured by crossing a border. Building her dome with real Philadelphia systems reveals the immigrant experience at ground level.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Jende Jonga',
    real_or_fictional: 'fictional',
    source_work: 'Behold the Dreamers',
    source_author_creator: 'Imbolo Mbue',
    source_year: 2016,
    circumstances: ['immigrant', 'asylum_seeker', 'poverty', 'housing_insecure'],
    location: 'Harlem, New York City, NY; Limbe, Cameroon',
    time_period: '2007-2009 (financial crisis)',
    systems_touched: ['immigration court', 'asylum process', 'Lehman Brothers (employer\'s employer)', 'taxi/car service economy', 'churches', 'schools'],
    dome_layer_richness: { 1: 9, 2: 7, 3: 7, 4: 4, 5: 6, 6: 7, 7: 5, 8: 7, 9: 4, 10: 7, 11: 4, 12: 6 },
    key_relationships: ['Neni (wife)', 'Liomi (son)', 'Clark Edwards (employer)', 'Cindy Edwards', 'Immigration lawyer'],
    narrative_arc: 'Cameroonian immigrant working as a chauffeur for a Lehman Brothers executive during the 2008 financial crisis. Mbue documents two domes collapsing simultaneously — the immigrant family losing their asylum case while the American family loses their wealth. The intersection reveals that both systems — immigration and finance — are equally precarious.',
    why_this_character_matters: 'Jende\'s dome maps the immigration-employment nexus during economic crisis. Layer 1 (Legal — asylum) and Layer 6 (Economic — the crash) collapse simultaneously, revealing how immigrant domes are doubly exposed to systemic shocks.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'Winston Smith',
    real_or_fictional: 'fictional',
    source_work: '1984',
    source_author_creator: 'George Orwell',
    source_year: 1949,
    circumstances: ['surveillance', 'poverty', 'housing_insecure', 'forced_labor'],
    location: 'Airstrip One (London), Oceania',
    time_period: '1984',
    systems_touched: ['Ministry of Truth', 'Thought Police', 'telescreen surveillance', 'Victory Mansions (housing)', 'canteen system', 'lottery'],
    dome_layer_richness: { 1: 9, 2: 8, 3: 5, 4: 6, 5: 7, 6: 7, 7: 5, 8: 6, 9: 6, 10: 10, 11: 6, 12: 7 },
    key_relationships: ['Julia', 'O\'Brien', 'Big Brother', 'Syme', 'Parsons'],
    narrative_arc: 'Party member who secretly rebels against total surveillance. Orwell documents the infrastructure of totalitarian control — the telescreen in every room, the Newspeak that eliminates dissenting thoughts, the memory holes that rewrite history, the Two Minutes Hate that redirects anger. Winston\'s rebellion is an attempt to fill Layers 10-12 in a system designed to empty them.',
    why_this_character_matters: 'Winston\'s dome maps total state control. Every layer is managed by a different Ministry — Truth (information), Peace (war), Love (torture), Plenty (scarcity). His dome is the theoretical maximum of system penetration into a life.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },

  {
    name: 'K (Josef K.)',
    real_or_fictional: 'fictional',
    source_work: 'The Trial',
    source_author_creator: 'Franz Kafka',
    source_year: 1925,
    circumstances: ['detained', 'surveillance'],
    location: 'Prague (unspecified city)',
    time_period: '1910s',
    systems_touched: ['courts (secret)', 'bank (employer)', 'lawyers', 'court painters', 'prison chaplain'],
    dome_layer_richness: { 1: 10, 2: 8, 3: 4, 4: 4, 5: 4, 6: 6, 7: 4, 8: 5, 9: 4, 10: 9, 11: 3, 12: 6 },
    key_relationships: ['Court painter Titorelli', 'Lawyer Huld', 'Leni', 'Uncle Karl', 'Prison chaplain'],
    narrative_arc: 'Arrested for a crime that is never named by a court that never explains itself. Kafka documents the architecture of a legal system that exists to process people, not to deliver justice. K. navigates an infinite bureaucracy — every door opens onto another waiting room, every official defers to another official, the process is the punishment.',
    why_this_character_matters: 'K.\'s dome is Layer 1 (Legal) and Layer 2 (Systems) consuming all other layers. His dome maps what happens when bureaucracy becomes the primary condition of existence — when navigating the system IS the full-time job.',
    source_urls: [],
    scraped_at: new Date().toISOString(),
  },
]
